const fs = require('fs');
const path = require('path');

const projectRoot = __dirname;
const seedPath = path.join(projectRoot, 'apps', 'server', 'prisma', 'seed.ts');

let content = fs.readFileSync(seedPath, 'utf8');

// Define new systems JS array text to append
const newSystemsText = `
    // ---- Added Missing International Systems ----
    {
      name: 'S-500 Prometey',
      countryOfOrigin: 'Russia',
      category: 'LONG_RANGE' as const,
      minRange: 5,
      maxRange: 600,
      minAltitude: 10,
      maxAltitude: 40000,
      radarType: '91N6A(M) Big Bird + 96L6-TsP AESA',
      missileType: '77N6-N / 77N6-N1',
      mobilityClass: 'SEMI_MOBILE' as const,
      serviceEntryYear: 2021,
      cost: 1500,
      operatingCostPerHour: 8000,
      reloadTime: 20,
      maxSimultaneousTargets: 10,
      accuracy: 0.95,
      interceptorSpeed: 20.0,
      description: 'S-500 Prometey is Russia\\'s next-generation strategic air defence and anti-ballistic missile system designed to intercept hypersonic missiles and low-orbit satellites.',
      isIndian: false,
    },
    {
      name: 'S-350E Vityaz',
      countryOfOrigin: 'Russia',
      category: 'MEDIUM_RANGE' as const,
      minRange: 1.5,
      maxRange: 120,
      minAltitude: 10,
      maxAltitude: 30000,
      radarType: '50N6A Multi-Function AESA',
      missileType: '9M96E2 / 9M100',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 2019,
      cost: 400,
      operatingCostPerHour: 2800,
      reloadTime: 10,
      maxSimultaneousTargets: 16,
      accuracy: 0.90,
      interceptorSpeed: 4.5,
      description: 'S-350E Vityaz is an agile medium-range SAM system replacing older S-300PS variants, optimized against cruise missiles, precision-guided munitions, and UAVs.',
      isIndian: false,
    },
    {
      name: 'Pantsir-S1',
      countryOfOrigin: 'Russia',
      category: 'SHORT_RANGE' as const,
      minRange: 1,
      maxRange: 20,
      minAltitude: 15,
      maxAltitude: 15000,
      radarType: '1RS2-1E Phased Array',
      missileType: '57E6 / 30mm 2A38M Guns',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 2008,
      cost: 14,
      operatingCostPerHour: 400,
      reloadTime: 5,
      maxSimultaneousTargets: 4,
      accuracy: 0.88,
      interceptorSpeed: 3.8,
      description: 'Pantsir-S1 is a truck-mounted short-range air defence system combining twelve 57E6 radio-command guided missiles and two twin 30mm autocannons for close-in protection.',
      isIndian: false,
    },
    {
      name: '55G6 Tall Rack Radar',
      countryOfOrigin: 'Russia',
      category: 'RADAR' as const,
      minRange: 10,
      maxRange: 600,
      minAltitude: 0,
      maxAltitude: 30000,
      radarType: '55G6 Nebo-M 3D AESA',
      missileType: 'None',
      mobilityClass: 'SEMI_MOBILE' as const,
      serviceEntryYear: 2015,
      cost: 40,
      operatingCostPerHour: 300,
      reloadTime: 0,
      maxSimultaneousTargets: 200,
      accuracy: 0,
      interceptorSpeed: 0,
      description: 'The 55G6 (Nebo-M) is a multi-band radar system specializing in detecting stealth aircraft, cruise missiles, and ballistic targets at long ranges.',
      isIndian: false,
    },
    {
      name: 'Patriot PAC-3 MSE (JASDF)',
      countryOfOrigin: 'Japan',
      category: 'LONG_RANGE' as const,
      minRange: 2,
      maxRange: 160,
      minAltitude: 10,
      maxAltitude: 30000,
      radarType: 'AN/MPQ-65 Fire Control Radar',
      missileType: 'PAC-3 MSE',
      mobilityClass: 'SEMI_MOBILE' as const,
      serviceEntryYear: 2015,
      cost: 1000,
      operatingCostPerHour: 4500,
      reloadTime: 15,
      maxSimultaneousTargets: 36,
      accuracy: 0.93,
      interceptorSpeed: 5.0,
      description: 'The Patriot PAC-3 MSE is JASDF\\'s primary long-range interceptor and ballistic missile defence system, deployed across major bases in Japan.',
      isIndian: false,
    },
    {
      name: 'Type-03 Chū-SAM',
      countryOfOrigin: 'Japan',
      category: 'MEDIUM_RANGE' as const,
      minRange: 1.5,
      maxRange: 90,
      minAltitude: 15,
      maxAltitude: 20000,
      radarType: 'Active Phase Array Radar',
      missileType: 'Type-03 Active Radar SAM',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 2005,
      cost: 100,
      operatingCostPerHour: 1000,
      reloadTime: 8,
      maxSimultaneousTargets: 12,
      accuracy: 0.87,
      interceptorSpeed: 2.5,
      description: 'The Type-03 Chū-SAM is a Japanese medium-range air defence system deployed by the JGSDF, using active radar homing interceptors.',
      isIndian: false,
    },
    {
      name: 'Type-11 SAM',
      countryOfOrigin: 'Japan',
      category: 'SHORT_RANGE' as const,
      minRange: 1,
      maxRange: 10,
      minAltitude: 10,
      maxAltitude: 8000,
      radarType: 'Type-11 Mobile Fire Control',
      missileType: 'Type-11 active radar-guided',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 2011,
      cost: 15,
      operatingCostPerHour: 200,
      reloadTime: 4,
      maxSimultaneousTargets: 4,
      accuracy: 0.82,
      interceptorSpeed: 2.0,
      description: 'Type-11 is a short-range air defence system of the Japan Ground Self-Defense Force designed for defending bases and mobile forces.',
      isIndian: false,
    },
    {
      name: 'FPS-3 Radar',
      countryOfOrigin: 'Japan',
      category: 'RADAR' as const,
      minRange: 10,
      maxRange: 600,
      minAltitude: 0,
      maxAltitude: 30000,
      radarType: 'J/FPS-3 Active Phased Array',
      missileType: 'None',
      mobilityClass: 'STATIC' as const,
      serviceEntryYear: 1991,
      cost: 50,
      operatingCostPerHour: 200,
      reloadTime: 0,
      maxSimultaneousTargets: 100,
      accuracy: 0,
      interceptorSpeed: 0,
      description: 'The J/FPS-3 is Japan\\'s early warning and air surveillance 3D active electronically scanned array radar system operated by the JASDF.',
      isIndian: false,
    },
    {
      name: 'Patriot PAC-3 (ROKAF)',
      countryOfOrigin: 'South Korea',
      category: 'LONG_RANGE' as const,
      minRange: 2,
      maxRange: 160,
      minAltitude: 10,
      maxAltitude: 30000,
      radarType: 'AN/MPQ-65 Fire Control Radar',
      missileType: 'PAC-3 MSE / GEM-T',
      mobilityClass: 'SEMI_MOBILE' as const,
      serviceEntryYear: 2008,
      cost: 1000,
      operatingCostPerHour: 4500,
      reloadTime: 15,
      maxSimultaneousTargets: 36,
      accuracy: 0.93,
      interceptorSpeed: 5.0,
      description: 'ROKAF Patriot PAC-3 battery forms the core of South Korea\\'s lower-tier missile defence network against regional ballistic threats.',
      isIndian: false,
    },
    {
      name: 'Chun Ma II',
      countryOfOrigin: 'South Korea',
      category: 'SHORT_RANGE' as const,
      minRange: 0.5,
      maxRange: 10,
      minAltitude: 10,
      maxAltitude: 5000,
      radarType: 'Chun Ma Doppler Search Radar',
      missileType: 'Pegasus Command-to-Line-of-Sight',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 1999,
      cost: 10,
      operatingCostPerHour: 300,
      reloadTime: 4,
      maxSimultaneousTargets: 2,
      accuracy: 0.82,
      interceptorSpeed: 2.6,
      description: 'Chun Ma (K-SAM Pegasus) is South Korea\\'s short-range mobile surface-to-air missile system combining eight missiles and search/track radars on a tracked chassis.',
      isIndian: false,
    },
    {
      name: 'Sky Sabre (CAMM-ER)',
      countryOfOrigin: 'UK',
      category: 'LONG_RANGE' as const,
      minRange: 1.0,
      maxRange: 45,
      minAltitude: 10,
      maxAltitude: 12000,
      radarType: 'Saab Giraffe AMB AESA',
      missileType: 'CAMM-ER (Extended Range)',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 2021,
      cost: 200,
      operatingCostPerHour: 1200,
      reloadTime: 8,
      maxSimultaneousTargets: 24,
      accuracy: 0.91,
      interceptorSpeed: 3.0,
      description: 'Sky Sabre (CAMM-ER) configuration extends the baseline British Army air defence capability with longer range active-radar homing interceptors.',
      isIndian: false,
    },
    {
      name: 'Land Ceptor CAMM',
      countryOfOrigin: 'UK',
      category: 'MEDIUM_RANGE' as const,
      minRange: 0.5,
      maxRange: 25,
      minAltitude: 10,
      maxAltitude: 10000,
      radarType: 'Saab Giraffe AMB AESA',
      missileType: 'CAMM standard',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 2021,
      cost: 80,
      operatingCostPerHour: 800,
      reloadTime: 6,
      maxSimultaneousTargets: 24,
      accuracy: 0.89,
      interceptorSpeed: 3.0,
      description: 'Land Ceptor is the British Army variant of the Common Anti-air Modular Missile (CAMM) deployed on transportable launcher trucks.',
      isIndian: false,
    },
    {
      name: 'Rapier FSC',
      countryOfOrigin: 'UK',
      category: 'SHORT_RANGE' as const,
      minRange: 0.5,
      maxRange: 8,
      minAltitude: 15,
      maxAltitude: 5000,
      radarType: 'Dagger 3D Surveillance Radar',
      missileType: 'Rapier Mk2 CLOS',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 1996,
      cost: 8,
      operatingCostPerHour: 200,
      reloadTime: 4,
      maxSimultaneousTargets: 2,
      accuracy: 0.78,
      interceptorSpeed: 2.5,
      description: 'Rapier Field Standard C (FSC) is a legacy British short-range mobile SAM system utilizing optical and radar tracking with command-to-line-of-sight missiles.',
      isIndian: false,
    },
    {
      name: 'Starstreak HVM',
      countryOfOrigin: 'UK',
      category: 'VERY_SHORT_RANGE' as const,
      minRange: 0.3,
      maxRange: 7,
      minAltitude: 5,
      maxAltitude: 5000,
      radarType: 'Optical ADAD Tracker',
      missileType: 'Starstreak Laser-guided Darts',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 1997,
      cost: 0.5,
      operatingCostPerHour: 50,
      reloadTime: 2,
      maxSimultaneousTargets: 1,
      accuracy: 0.87,
      interceptorSpeed: 4.0,
      description: 'Starstreak High Velocity Missile (HVM) utilizes laser beam riding guidance to launch three tungsten alloy darts at speeds exceeding Mach 3.0.',
      isIndian: false,
    },
    {
      name: 'SAMP/T (Aster 30)',
      countryOfOrigin: 'France',
      category: 'LONG_RANGE' as const,
      minRange: 3,
      maxRange: 120,
      minAltitude: 15,
      maxAltitude: 20000,
      radarType: 'Arabel PESA Multi-Function Radar',
      missileType: 'Aster 30 Active Radar-Guided',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 2001,
      cost: 500,
      operatingCostPerHour: 3000,
      reloadTime: 12,
      maxSimultaneousTargets: 16,
      accuracy: 0.90,
      interceptorSpeed: 4.5,
      description: 'SAMP/T is a French-Italian long-range truck-mounted SAM system utilizing the Aster 30 missile with active radar seeker and PIF-PAF thrusters for high terminal maneuverability.',
      isIndian: false,
    },
    {
      name: 'VL MICA',
      countryOfOrigin: 'France',
      category: 'MEDIUM_RANGE' as const,
      minRange: 1,
      maxRange: 25,
      minAltitude: 10,
      maxAltitude: 10000,
      radarType: 'Tactical Multi-Function Radar',
      missileType: 'MICA RF / IR',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 2010,
      cost: 50,
      operatingCostPerHour: 500,
      reloadTime: 6,
      maxSimultaneousTargets: 8,
      accuracy: 0.88,
      interceptorSpeed: 3.0,
      description: 'Vertical Launch MICA (VL MICA) is a short-to-medium range mobile SAM system utilizing active radar-homing (RF) or imaging infrared (IR) MICA interceptors.',
      isIndian: false,
    },
    {
      name: 'Crotale NG',
      countryOfOrigin: 'France',
      category: 'SHORT_RANGE' as const,
      minRange: 0.5,
      maxRange: 11,
      minAltitude: 15,
      maxAltitude: 6000,
      radarType: 'Pulse Doppler Search & Track',
      missileType: 'VT1 Command-to-Line-of-Sight',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 1990,
      cost: 20,
      operatingCostPerHour: 250,
      reloadTime: 4,
      maxSimultaneousTargets: 2,
      accuracy: 0.82,
      interceptorSpeed: 3.5,
      description: 'Crotale NG is an all-weather short-range mobile SAM system deploying VT1 high-velocity hyper-maneuverable missiles.',
      isIndian: false,
    },
    {
      name: 'Mistral VSHORAD',
      countryOfOrigin: 'France',
      category: 'VERY_SHORT_RANGE' as const,
      minRange: 0.5,
      maxRange: 6,
      minAltitude: 5,
      maxAltitude: 3000,
      radarType: 'Optical Target Sight',
      missileType: 'Mistral Infrared Homing',
      mobilityClass: 'MANPORTABLE' as const,
      serviceEntryYear: 1989,
      cost: 0.3,
      operatingCostPerHour: 30,
      reloadTime: 2,
      maxSimultaneousTargets: 1,
      accuracy: 0.85,
      interceptorSpeed: 2.5,
      description: 'Mistral is a French fire-and-forget man-portable or vehicle-mounted VSHORAD system utilizing a highly sensitive infrared imaging seeker.',
      isIndian: false,
    },
    {
      name: 'IRIS-T SLX',
      countryOfOrigin: 'Germany',
      category: 'LONG_RANGE' as const,
      minRange: 1.0,
      maxRange: 80,
      minAltitude: 10,
      maxAltitude: 30000,
      radarType: 'TRML-4D AESA 360°',
      missileType: 'IRIS-T SLX active-seeker',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 2024,
      cost: 500,
      operatingCostPerHour: 2200,
      reloadTime: 12,
      maxSimultaneousTargets: 12,
      accuracy: 0.91,
      interceptorSpeed: 3.0,
      description: 'IRIS-T SLX is the long-range variant of the IRIS-T SAM family co-developed by Germany, combining dual-mode active radar/infrared terminal guidance.',
      isIndian: false,
    },
    {
      name: 'IRIS-T SLS Short',
      countryOfOrigin: 'Germany',
      category: 'SHORT_RANGE' as const,
      minRange: 0.5,
      maxRange: 12,
      minAltitude: 10,
      maxAltitude: 8000,
      radarType: 'Giraffe 1X Mobile Search',
      missileType: 'IRIS-T SLS infrared',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 2015,
      cost: 20,
      operatingCostPerHour: 300,
      reloadTime: 4,
      maxSimultaneousTargets: 4,
      accuracy: 0.88,
      interceptorSpeed: 3.0,
      description: 'IRIS-T SLS is the short-range variant deploying standard IRIS-T air-to-air missiles directly from wheeled container cells without booster modifications.',
      isIndian: false,
    },
    {
      name: 'Ozelot VSHORAD',
      countryOfOrigin: 'Germany',
      category: 'VERY_SHORT_RANGE' as const,
      minRange: 0.5,
      maxRange: 6,
      minAltitude: 10,
      maxAltitude: 5000,
      radarType: 'HARD 3D Search Radar',
      missileType: 'FIM-92 Stinger IR homing',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 2001,
      cost: 3,
      operatingCostPerHour: 80,
      reloadTime: 2,
      maxSimultaneousTargets: 1,
      accuracy: 0.82,
      interceptorSpeed: 2.2,
      description: 'Ozelot is a light tracked vehicle deploying four Stinger VSHORAD missiles, providing mobile point-defence for armored forces.',
      isIndian: false,
    },
`;

// Insert new systems into the systems array
const systemInsertIndex = content.indexOf('for (const system of systems)');
if (systemInsertIndex !== -1) {
  const systemsEndIndex = content.lastIndexOf('];', systemInsertIndex);
  if (systemsEndIndex !== -1) {
    content = content.substring(0, systemsEndIndex) + newSystemsText + content.substring(systemsEndIndex);
    console.log("Seeded new systems in seed.ts.");
  } else {
    console.error("Could not find systems array end bracket.");
  }
} else {
  console.error("Could not find system insertion marker.");
}

// Define new threats JS array text to append
const newThreatsText = `
    // ---- Added Missing International Aircraft & Drones ----
    {
      name: 'F-35A Lightning II (JASDF)',
      type: 'FIGHTER_AIRCRAFT' as const,
      countryOfOrigin: 'Japan',
      speedClass: 'SUPERSONIC' as const,
      maxSpeed: 1.6,
      altitudeClass: 'HIGH' as const,
      minAltitude: 50,
      maxAltitude: 18300,
      radarVisibility: 'STEALTH' as const,
      rcs: 0.001,
      threatScore: 93,
      costEstimate: 80000,
      range: 2200,
      warheadWeight: 8165,
      description: 'F-35A conventional take-off and landing stealth fighter operated by the Japan Air Self-Defense Force with state-of-the-art radar and sensor fusion.',
    },
    {
      name: 'F-35B Lightning II (JASDF STOVL)',
      type: 'FIGHTER_AIRCRAFT' as const,
      countryOfOrigin: 'Japan',
      speedClass: 'SUPERSONIC' as const,
      maxSpeed: 1.6,
      altitudeClass: 'HIGH' as const,
      minAltitude: 50,
      maxAltitude: 15240,
      radarVisibility: 'STEALTH' as const,
      rcs: 0.0015,
      threatScore: 91,
      costEstimate: 95000,
      range: 1670,
      warheadWeight: 6800,
      description: 'F-35B short take-off and vertical landing stealth fighter variant operated by the JASDF from Izumo-class helicopter destroyers.',
    },
    {
      name: 'F-2A Viper Zero (JASDF)',
      type: 'FIGHTER_AIRCRAFT' as const,
      countryOfOrigin: 'Japan',
      speedClass: 'SUPERSONIC' as const,
      maxSpeed: 2.0,
      altitudeClass: 'HIGH' as const,
      minAltitude: 50,
      maxAltitude: 18000,
      radarVisibility: 'MEDIUM' as const,
      rcs: 1.2,
      threatScore: 75,
      costEstimate: 100000,
      range: 830,
      warheadWeight: 8000,
      description: 'JASDF multirole fighter based on the F-16 design, co-developed by Mitsubishi and Lockheed Martin, featuring the J/APG-1/2 AESA radar.',
    },
    {
      name: 'RQ-4B Global Hawk (JASDF)',
      type: 'UAV' as const,
      countryOfOrigin: 'Japan',
      speedClass: 'SUBSONIC' as const,
      maxSpeed: 0.5,
      altitudeClass: 'HIGH' as const,
      minAltitude: 100,
      maxAltitude: 18000,
      radarVisibility: 'LOW' as const,
      rcs: 0.25,
      threatScore: 55,
      costEstimate: 120000,
      range: 22000,
      warheadWeight: 0,
      description: 'High-altitude long-endurance unmanned aerial vehicle operated by the JASDF for national surveillance and intelligence gathering.',
    },
    {
      name: 'KF-21 Boramae (ROKAF)',
      type: 'FIGHTER_AIRCRAFT' as const,
      countryOfOrigin: 'South Korea',
      speedClass: 'SUPERSONIC' as const,
      maxSpeed: 1.8,
      altitudeClass: 'HIGH' as const,
      minAltitude: 50,
      maxAltitude: 16700,
      radarVisibility: 'LOW' as const,
      rcs: 0.05,
      threatScore: 85,
      costEstimate: 65000,
      range: 2900,
      warheadWeight: 7700,
      description: 'South Korea\\'s indigenous advanced 4.5-generation fighter featuring low-observable shaping, AESA radar, and internal weapons bay capability.',
    },
    {
      name: 'F-15K Slam Eagle (ROKAF)',
      type: 'FIGHTER_AIRCRAFT' as const,
      countryOfOrigin: 'South Korea',
      speedClass: 'SUPERSONIC' as const,
      maxSpeed: 2.5,
      altitudeClass: 'HIGH' as const,
      minAltitude: 50,
      maxAltitude: 18300,
      radarVisibility: 'HIGH' as const,
      rcs: 4.2,
      threatScore: 83,
      costEstimate: 100000,
      range: 1800,
      warheadWeight: 10400,
      description: 'ROKAF\\'s heavy multirole strike fighter variant of the F-15E, optimized for deep precision strike missions and armed with Slam-ER missiles.',
    },
    {
      name: 'RQ-4 Block 30 Global Hawk (ROKAF)',
      type: 'UAV' as const,
      countryOfOrigin: 'South Korea',
      speedClass: 'SUBSONIC' as const,
      maxSpeed: 0.5,
      altitudeClass: 'HIGH' as const,
      minAltitude: 100,
      maxAltitude: 18000,
      radarVisibility: 'LOW' as const,
      rcs: 0.25,
      threatScore: 55,
      costEstimate: 120000,
      range: 22000,
      warheadWeight: 0,
      description: 'High-altitude long-endurance surveillance UAV operated by the Republic of Korea Air Force to monitor territorial borders.',
    },
    {
      name: 'Eurofighter Typhoon FGR4 (RAF)',
      type: 'FIGHTER_AIRCRAFT' as const,
      countryOfOrigin: 'UK',
      speedClass: 'SUPERSONIC' as const,
      maxSpeed: 2.0,
      altitudeClass: 'HIGH' as const,
      minAltitude: 50,
      maxAltitude: 19800,
      radarVisibility: 'LOW' as const,
      rcs: 1.0,
      threatScore: 85,
      costEstimate: 90000,
      range: 2900,
      warheadWeight: 7500,
      description: 'RAF\\'s multirole delta-wing air superiority fighter, equipped with Captor-M/E radar, PIRATE IRST, Meteor BVRAAM, and Storm Shadow LACM.',
    },
    {
      name: 'F-35B Lightning II (RAF)',
      type: 'FIGHTER_AIRCRAFT' as const,
      countryOfOrigin: 'UK',
      speedClass: 'SUPERSONIC' as const,
      maxSpeed: 1.6,
      altitudeClass: 'HIGH' as const,
      minAltitude: 50,
      maxAltitude: 15240,
      radarVisibility: 'STEALTH' as const,
      rcs: 0.0015,
      threatScore: 92,
      costEstimate: 95000,
      range: 1670,
      warheadWeight: 6800,
      description: 'UK Joint Force Lightning STOVL stealth multirole fighter, flying from HMS Queen Elizabeth aircraft carriers.',
    },
    {
      name: 'MQ-9A Reaper (RAF)',
      type: 'UAV' as const,
      countryOfOrigin: 'UK',
      speedClass: 'SUBSONIC' as const,
      maxSpeed: 0.4,
      altitudeClass: 'HIGH' as const,
      minAltitude: 100,
      maxAltitude: 15240,
      radarVisibility: 'LOW' as const,
      rcs: 0.28,
      threatScore: 58,
      costEstimate: 16000,
      range: 1850,
      warheadWeight: 1700,
      description: 'Royal Air Force armed medium-altitude long-endurance UAV carrying Hellfire missiles and Paveway guided bombs.',
    },
    {
      name: 'Rafale C (French Air Force)',
      type: 'FIGHTER_AIRCRAFT' as const,
      countryOfOrigin: 'France',
      speedClass: 'SUPERSONIC' as const,
      maxSpeed: 1.8,
      altitudeClass: 'HIGH' as const,
      minAltitude: 50,
      maxAltitude: 15800,
      radarVisibility: 'LOW' as const,
      rcs: 0.5,
      threatScore: 85,
      costEstimate: 85000,
      range: 3700,
      warheadWeight: 9500,
      description: 'French Air Force single-seat delta-wing multirole fighter featuring Spectra EW suite, RBE2 AESA radar, and Meteor BVRAAM capacity.',
    },
    {
      name: 'Rafale M (French Navy)',
      type: 'FIGHTER_AIRCRAFT' as const,
      countryOfOrigin: 'France',
      speedClass: 'SUPERSONIC' as const,
      maxSpeed: 1.8,
      altitudeClass: 'HIGH' as const,
      minAltitude: 50,
      maxAltitude: 15800,
      radarVisibility: 'LOW' as const,
      rcs: 0.52,
      threatScore: 86,
      costEstimate: 90000,
      range: 3700,
      warheadWeight: 9500,
      description: 'Carrier-capable variant of the Rafale operated by the French Navy from the Charles de Gaulle aircraft carrier.',
    },
    {
      name: 'Mirage 2000-5F (French Air Force)',
      type: 'FIGHTER_AIRCRAFT' as const,
      countryOfOrigin: 'France',
      speedClass: 'SUPERSONIC' as const,
      maxSpeed: 2.2,
      altitudeClass: 'HIGH' as const,
      minAltitude: 50,
      maxAltitude: 18000,
      radarVisibility: 'MEDIUM' as const,
      rcs: 1.5,
      threatScore: 72,
      costEstimate: 40000,
      range: 1550,
      warheadWeight: 6300,
      description: 'Upgraded French air superiority variant of the Mirage 2000 featuring RDY radar and MICA active radar BVRAAMs.',
    },
    {
      name: 'nEUROn UCAV (Stealth Drone)',
      type: 'UAV' as const,
      countryOfOrigin: 'France',
      speedClass: 'SUBSONIC' as const,
      maxSpeed: 0.85,
      altitudeClass: 'HIGH' as const,
      minAltitude: 50,
      maxAltitude: 14000,
      radarVisibility: 'STEALTH' as const,
      rcs: 0.005,
      threatScore: 75,
      costEstimate: 25000,
      range: 2000,
      warheadWeight: 1000,
      description: 'French stealth unmanned combat aerial vehicle demonstrator featuring flying wing aerodynamics and internal weapons bay.',
    },
    {
      name: 'Eurofighter Typhoon (Luftwaffe)',
      type: 'FIGHTER_AIRCRAFT' as const,
      countryOfOrigin: 'Germany',
      speedClass: 'SUPERSONIC' as const,
      maxSpeed: 2.0,
      altitudeClass: 'HIGH' as const,
      minAltitude: 50,
      maxAltitude: 19800,
      radarVisibility: 'LOW' as const,
      rcs: 1.0,
      threatScore: 84,
      costEstimate: 90000,
      range: 2900,
      warheadWeight: 7500,
      description: 'German Luftwaffe twin-engine delta-wing multirole fighter configuration deployed for European air defence.',
    },
    {
      name: 'Panavia Tornado IDS (Luftwaffe)',
      type: 'FIGHTER_AIRCRAFT' as const,
      countryOfOrigin: 'Germany',
      speedClass: 'SUPERSONIC' as const,
      maxSpeed: 2.2,
      altitudeClass: 'HIGH' as const,
      minAltitude: 30,
      maxAltitude: 15000,
      radarVisibility: 'HIGH' as const,
      rcs: 6.0,
      threatScore: 68,
      costEstimate: 35000,
      range: 1390,
      warheadWeight: 9000,
      description: 'German Luftwaffe variable-sweep wing strike fighter optimized for low-level high-speed penetration and stand-off attacks.',
    },
    {
      name: 'Heron TP (Luftwaffe UAV)',
      type: 'UAV' as const,
      countryOfOrigin: 'Germany',
      speedClass: 'SUBSONIC' as const,
      maxSpeed: 0.35,
      altitudeClass: 'HIGH' as const,
      minAltitude: 100,
      maxAltitude: 13700,
      radarVisibility: 'LOW' as const,
      rcs: 0.35,
      threatScore: 52,
      costEstimate: 12000,
      range: 7400,
      warheadWeight: 450,
      description: 'Medium-altitude long-endurance UAV leased by the Luftwaffe, capable of reconnaissance and carrying precision strikes.',
    },
`;

// Insert new threats into the threats array
const threatInsertIndex = content.indexOf('for (const threat of threats)');
if (threatInsertIndex !== -1) {
  const threatsEndIndex = content.lastIndexOf('];', threatInsertIndex);
  if (threatsEndIndex !== -1) {
    content = content.substring(0, threatsEndIndex) + newThreatsText + content.substring(threatsEndIndex);
    console.log("Seeded new threats in seed.ts.");
  } else {
    console.error("Could not find threats array end bracket.");
  }
} else {
  console.error("Could not find threat insertion marker.");
}

fs.writeFileSync(seedPath, content, 'utf8');
console.log("Done seeding data to seed.ts successfully.");
