// ============================================
// IADES — Equipment Image URL Mapping
// AUTO-GENERATED and merged from Wikipedia/Commons logs
// ============================================

const WIKI_IMAGES: Record<string, string> = {
  "S-400 Triumf Regiment": "https://upload.wikimedia.org/wikipedia/commons/9/94/%D0%A1-400_%C2%AB%D0%A2%D1%80%D0%B8%D1%83%D0%BC%D1%84%C2%BB.JPG",
  "Barak 8 ER SAM Regiment": "https://upload.wikimedia.org/wikipedia/commons/f/f6/Salon_du_Bourget_20090619_077.jpg",
  "MRSAM / Barak-8 Regiment": "https://upload.wikimedia.org/wikipedia/commons/f/f6/Salon_du_Bourget_20090619_077.jpg",
  "Akash-NG Regiment": "https://upload.wikimedia.org/wikipedia/commons/3/3e/Akash_NG_being_flight_tested_%28cropped%29.jpg",
  "Akash SAM Regiment": "https://upload.wikimedia.org/wikipedia/commons/7/7d/AkashPrimeSAM.jpg",
  "Pechora-2M SAM Battery": "https://upload.wikimedia.org/wikipedia/en/5/58/SA-3_EP_2006.JPG",
  "SPYDER SAM Battery": "https://upload.wikimedia.org/wikipedia/commons/d/df/SPYDER.jpg",
  "QRSAM Regiment": "https://upload.wikimedia.org/wikipedia/commons/9/94/Second_test_of_DRDO_QRSAM_%28cropped%29.jpg",
  "VSHORAD MANPADS Team": "https://upload.wikimedia.org/wikipedia/commons/0/0d/Maiden_launch_of_Very_Short_Range_Air_Defence_System_%28VSHORADS%29_missile_%28cropped%29.jpg",
  "Igla-S MANPADS Team": "https://upload.wikimedia.org/wikipedia/commons/c/cc/IGLA-S_MANPADS_at_IDELF-2008.jpg",
  "Arudhra AESA Radar Station": "https://upload.wikimedia.org/wikipedia/commons/8/85/Rohini_radar.jpg",
  "LY-80 LOMADS Regiment": "https://upload.wikimedia.org/wikipedia/commons/6/60/HQ-16A_Surface-to-air_missiles_20170919.jpg",
  "Spada 2000 SAM Battery": "https://upload.wikimedia.org/wikipedia/commons/5/53/Misil_Aspide.jpg",
  "FM-90 SAM Battery": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Bangladesh_Air_Force_FM-90_Crotale_SAM_%2831545368571%29.jpg",
  "Anza Mk-III MANPADS Team": "https://upload.wikimedia.org/wikipedia/commons/f/f7/ANZA_MK_2.JPG",
  "TPS-77 Radar Station": "https://upload.wikimedia.org/wikipedia/commons/0/02/RAAF_AN-FPS-117_radar_in_2007.jpg",
  "Patriot PAC-3 MSE Battery": "https://upload.wikimedia.org/wikipedia/commons/2/2f/U-s-service-members-stand-by-a-patriot-missile-battery-in-gaziantep-turkey.jpg",
  "NASAMS III Battery": "https://upload.wikimedia.org/wikipedia/commons/d/d9/Norwegian_Advanced_Surface_to_Air_Missile_System.jpg",
  "THAAD Battery": "https://upload.wikimedia.org/wikipedia/commons/4/45/The_first_of_two_Terminal_High_Altitude_Area_Defense_%28THAAD%29_interceptors_is_launched_during_a_successful_intercept_test_-_US_Army.jpg",
  "Avenger SHORAD Battery": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Voorzijde_van_een_Stinger_lanceerbuis_met_richt-afvuurapparatuur_%282086-065-004%29.jpg",
  "Iron Dome Battery (US-acquired)": "https://upload.wikimedia.org/wikipedia/commons/0/08/IDF_Iron_Dome_2021.jpg",
  "AN/TPY-2 Radar Station": "https://upload.wikimedia.org/wikipedia/commons/f/f2/TPY-2_%28Forward_Based_X-Band_Radar%29.jpg",
  "HQ-9B Regiment": "https://upload.wikimedia.org/wikipedia/commons/d/d0/Chinese_HQ-9_launcher.jpg",
  "HQ-22 MRSAM Regiment": "https://upload.wikimedia.org/wikipedia/commons/0/04/Granit_2023_-_102_-_FK-3.jpg",
  "HQ-17A SAM Battery": "https://upload.wikimedia.org/wikipedia/commons/e/e4/Tor-M1_SAM_%282%29.jpg",
  "PGZ-09 SPAAA Battery": "https://upload.wikimedia.org/wikipedia/commons/0/0a/PGZ-09_Self-propelled_Anti-Aircrafft_Artillery_20170919.jpg",
  "YLC-2V Radar Station": "https://upload.wikimedia.org/wikipedia/commons/f/ff/Sri_Lanka_Military_0051.jpg",
  "HQ-9C LRAD Regiment": "https://upload.wikimedia.org/wikipedia/commons/d/d0/Chinese_HQ-9_launcher.jpg",
  "HQ-11 SAM Battery (Red Flag-11)": "https://upload.wikimedia.org/wikipedia/commons/6/60/HQ-11_in_Zhuhai_airshow_2024.jpg",
  "HQ-16B MRAD Regiment": "https://upload.wikimedia.org/wikipedia/commons/6/60/HQ-16A_Surface-to-air_missiles_20170919.jpg",
  "S-500 Prometey Regiment": "https://upload.wikimedia.org/wikipedia/commons/1/16/%D0%A1-500_%D1%80%D0%BE%D1%81%D1%81%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9_%D0%B7%D0%B5%D0%BD%D0%B8%D1%82%D0%BD%D1%8B%D0%B9_%D1%80%D0%B0%D0%BA%D0%B5%D1%82%D0%BD%D1%8B%D0%B9_%D0%BA%D0%BE%D0%BC%D0%BF%D0%BB%D0%B5%D0%BA%D1%81.jpg",
  "S-350E Vityaz Regiment": "https://upload.wikimedia.org/wikipedia/commons/7/75/MAKS2013firstpix02.jpg",
  "Pantsir-S1 Battery": "https://upload.wikimedia.org/wikipedia/commons/c/cf/MAKS_Airshow_2013_%28Ramenskoye_Airport%2C_Russia%29_%28521-05%29.jpg",
  "Tor-M2 SAM Battery": "https://upload.wikimedia.org/wikipedia/commons/e/e4/Tor-M1_SAM_%282%29.jpg",
  "55G6 Tall Rack Radar Station": "https://upload.wikimedia.org/wikipedia/commons/f/f4/AirFrontiers2018-27.jpg",
  "S-300PMU2 Favorit Regiment": "https://upload.wikimedia.org/wikipedia/commons/e/e5/S-300_-_2009_Moscow_Victory_Day_Parade_%282%29.jpg",
  "Buk-M3 Viking Regiment": "https://upload.wikimedia.org/wikipedia/commons/1/1a/Buk-M1-2_air_defence_system_in_2010.jpg",
  "Pantsir-S2 (SA-22) Battery": "https://upload.wikimedia.org/wikipedia/commons/c/cf/MAKS_Airshow_2013_%28Ramenskoye_Airport%2C_Russia%29_%28521-05%29.jpg",
  "Patriot PAC-3 MSE Battery (JASDF)": "https://upload.wikimedia.org/wikipedia/commons/2/2f/U-s-service-members-stand-by-a-patriot-missile-battery-in-gaziantep-turkey.jpg",
  "Type-03 Chū-SAM Battery": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JGSDF_Type03_Chu-SAM_launcher_unit_20120527-01.JPG",
  "Type-11 SAM Battery": "https://upload.wikimedia.org/wikipedia/commons/8/8b/JASDF_Type_11_SAM(Launcher)_in_Hamamatsu_Air_Base_20140928.JPG",
  "FPS-3 Radar Station": "https://upload.wikimedia.org/wikipedia/commons/a/a3/AN-FPS-20_Radar.jpg",
  "Patriot PAC-3 Battery (ROKAF)": "https://upload.wikimedia.org/wikipedia/commons/2/2f/U-s-service-members-stand-by-a-patriot-missile-battery-in-gaziantep-turkey.jpg",
  "Cheongung-II M-SAM Battery": "https://upload.wikimedia.org/wikipedia/commons/6/6a/A_scale_model_of_the_KM-SAM_Block_2_missile.jpg",
  "Chun Ma II Short-Range SAM": "https://upload.wikimedia.org/wikipedia/commons/7/77/Crotale_NG_P1220851.jpg",
  "Rapier FSC Battery": "https://upload.wikimedia.org/wikipedia/commons/1/1f/Swiss_rapier_missile.jpg",
  "Starstreak HVM Team": "https://upload.wikimedia.org/wikipedia/commons/0/05/CJOAX_fires_150417-A-BG594-015.jpg",
  "SAMP/T (Aster 30) Battery": "https://upload.wikimedia.org/wikipedia/commons/0/0d/MBDA_Aster_p1220947.jpg",
  "VL MICA Battery": "https://upload.wikimedia.org/wikipedia/commons/d/d5/MICA_P6230072.JPG",
  "Crotale NG Battery": "https://upload.wikimedia.org/wikipedia/commons/7/77/Crotale_NG_P1220851.jpg",
  "Mistral VSHORAD Team": "https://upload.wikimedia.org/wikipedia/commons/2/2c/Mistral_Atlas_launcher_of_the_Hungarian_Armed_Forces_cropped.jpg",
  "IRIS-T SLX Regiment": "https://upload.wikimedia.org/wikipedia/commons/4/44/IRIS-T_expo_front.JPG",
  "IRIS-T SLM Battery": "https://upload.wikimedia.org/wikipedia/commons/4/44/IRIS-T_expo_front.JPG",
  "Ozelot VSHORAD Battery": "https://upload.wikimedia.org/wikipedia/commons/5/52/LLWaTrg_Wiesel_1.JPG",
  "IRIS-T SLS Short Battery": "https://upload.wikimedia.org/wikipedia/commons/4/44/IRIS-T_expo_front.JPG",
  "Aegis Ashore (SM-3 Battery)": "https://upload.wikimedia.org/wikipedia/commons/3/35/Aegis_bmd_mda.jpg",
  "LPWS C-RAM (Centurion)": "https://upload.wikimedia.org/wikipedia/commons/8/8f/Phalanx_CIWS_Block_1B_Full_Sized_USS_Elrod_FFG-55.jpg",
  "HQ-19 ABM System": "https://upload.wikimedia.org/wikipedia/commons/c/c1/HQ-19_launcher_in_Zhuhai_airshow_2024.jpg",
  "LD-2000 C-RAM SPAAG": "https://upload.wikimedia.org/wikipedia/commons/a/a5/Bridge_of_CNS_Changchun_%28DDG-150%29.jpg",
  "Gibka-S Mobile VSHORAD": "https://upload.wikimedia.org/wikipedia/commons/c/c1/Zajedni%C4%8Dka_ve%C5%BEba_72_brSO_VS_i_2_br_Specnaz_OSRF_-_GAZ_Tigr_-_05.jpg",
  "Sosna-R Short-Range SAM": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Army-2018-56.jpg",
  "Type-03 Chū-SAM Kai": "https://upload.wikimedia.org/wikipedia/commons/6/6a/JGSDF_Type03_Chu-SAM_launcher_unit_20120527-01.JPG",
  "Type-81 Short Range SAM": "https://upload.wikimedia.org/wikipedia/commons/9/90/Type_81_SAM_-_launcher.jpg",
  "L-SAM ABM System": "https://upload.wikimedia.org/wikipedia/commons/5/5f/Long-range_Surface-to-Air_Missile.jpg",
  "LAMD (Low Altitude Missile Defense)": "https://upload.wikimedia.org/wikipedia/commons/c/c8/The_concept_of_Korean_Air_and_Missile_Defense.jpg",
  "Aegis Destroyer (SM-6 Type-45)": "https://upload.wikimedia.org/wikipedia/commons/b/bf/HMS_Daring-1.jpg",
  "Starstreak LML (VSHORAD)": "https://upload.wikimedia.org/wikipedia/commons/0/05/CJOAX_fires_150417-A-BG594-015.jpg",
  "VL MICA NG (Next-Generation)": "https://upload.wikimedia.org/wikipedia/commons/d/d5/MICA_P6230072.JPG",
  "Mistral Atlas Mobile VSHORAD": "https://upload.wikimedia.org/wikipedia/commons/2/2c/Mistral_Atlas_launcher_of_the_Hungarian_Armed_Forces_cropped.jpg",
  "Arrow 3 ABM System (German-acquired)": "https://upload.wikimedia.org/wikipedia/commons/d/de/IAF-Arrow-3-%D7%97%D7%A5-sq1666.jpg",
  "Mantis C-RAM Gun System": "https://upload.wikimedia.org/wikipedia/commons/9/90/Meppen_-_WTD91_%28TdBW%29_109_ies.jpg",
  "Shaheen-III": "https://upload.wikimedia.org/wikipedia/commons/c/ce/IRBM_of_Pakistan_at_IDEAS_2008.jpg",
  "DF-21D (Educational Reference)": "https://upload.wikimedia.org/wikipedia/commons/8/8f/DF-21A_TEL_-_Chinese_Military_Museum_Beijing.jpg",
  "Babur-3": "https://upload.wikimedia.org/wikipedia/commons/8/89/Babur_aa.jpg",
  "CJ-20 ALCM (Educational Reference)": "https://upload.wikimedia.org/wikipedia/commons/1/1f/CJ-20_cruise_missiles.jpg",
  "Wing Loong II": "https://upload.wikimedia.org/wikipedia/commons/0/0d/Wing_Loong_II_side_view.jpg",
  "Generic MALE UAV": "https://upload.wikimedia.org/wikipedia/commons/1/12/MQ-9_Reaper_UAV_%28cropped%29.jpg",
  "Generic Drone Swarm (50 units)": "/images/equipment/drone_swarm.png",
  "JF-17 Thunder Block III": "https://upload.wikimedia.org/wikipedia/commons/1/1b/Pakistan_Air_Force_Chengdu_JF-17_Gu.jpg",
  "J-10C (Educational Reference)": "https://upload.wikimedia.org/wikipedia/commons/7/77/J-10B_with_PL-10_and_PL-12.jpg",
  "F-16 Block 52+ (Educational Reference)": "https://upload.wikimedia.org/wikipedia/commons/c/c9/F-16_June_2008.jpg",
  "Agni-II": "https://upload.wikimedia.org/wikipedia/commons/9/96/Agni-II_missile_%28Republic_Day_Parade_2004%29.jpeg",
  "Agni-III": "https://upload.wikimedia.org/wikipedia/commons/4/44/Agni-III_Republic_day.jpg",
  "Agni-IV": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Agni-IV_2014_%28cropped%29.jpg",
  "Agni-V": "https://upload.wikimedia.org/wikipedia/commons/0/09/Agni-V_canistered_launch_on_rail_mobile_launcher_on_03_June_2018.jpg",
  "Prithvi-I": "https://upload.wikimedia.org/wikipedia/commons/6/69/Prithvi-II_missile_launch_on_11_March_2011_%28cropped%29.jpg",
  "Prithvi-II": "https://upload.wikimedia.org/wikipedia/commons/6/69/Prithvi-II_missile_launch_on_11_March_2011_%28cropped%29.jpg",
  "Prithvi-III": "https://upload.wikimedia.org/wikipedia/commons/f/f7/Dhanush_missile_launch_on_11_March_2011.jpg",
  "Prahaar": "https://upload.wikimedia.org/wikipedia/commons/0/0a/The_Defence_Research_and_Development_Organisation_%28DRDO%29_successfully_flight_testing_the_indigenously_developed_surface-to-surface_tactical_missile_%E2%80%98Prahar%E2%80%99%2C_from_Launch_Complex-III%2C_ITR%2C_Balasore%2C_in_Orissa_%28cropped%29.JPG",
  "Pragati": "https://upload.wikimedia.org/wikipedia/commons/0/0a/The_Defence_Research_and_Development_Organisation_(DRDO)_successfully_flight_testing_the_indigenously_developed_surface-to-surface_tactical_missile_‘Prahar’,_from_Launch_Complex-III,_ITR,_Balasore,_in_Orissa_(cropped).JPG",
  "Suryastra Heavy MLRS": "https://upload.wikimedia.org/wikipedia/commons/a/af/PULS_MLRS_Landmacht_1.jpg",
  "MiG-29UPG": "https://upload.wikimedia.org/wikipedia/commons/a/af/VVS_100th_IMG_0691_%287727464290%29_%28cropped%29.jpg",
  "Jaguar IS": "https://upload.wikimedia.org/wikipedia/commons/4/49/French_Jaguar_A_of_EC_1-7_Provence_in_flight_over_the_Adriatic_Sea%2C_8_April_2003_%28DF-SD-05-05511%29.jpg",
  "Minuteman III ICBM": "https://upload.wikimedia.org/wikipedia/commons/f/fe/LGM-30-Minuteman-II.jpg",
  "PrSM Tactical Missile": "https://upload.wikimedia.org/wikipedia/commons/c/c4/Precision_Strike_Missile_%28PrSM%29_Increment_1_Limited_User_Test.jpg",
  "DF-41 Heavy ICBM": "https://upload.wikimedia.org/wikipedia/commons/6/6f/120%E7%A7%92%E7%9C%8B%E5%A4%A7%E9%98%85%E5%85%B5%E9%9C%87%E6%92%BC%E7%9E%AC%E9%97%B4%EF%BC%811.png",
  "3M22 Zircon Hypersonic LACM": "https://upload.wikimedia.org/wikipedia/commons/f/f6/Zirkon_03.12.2024.jpg",
  "Tu-160M White Swan Bomber": "https://upload.wikimedia.org/wikipedia/commons/7/75/Tupolev_Tu-160_RF-94109.jpg",
  "Type-88 SSM Coastal Launcher": "https://upload.wikimedia.org/wikipedia/commons/4/48/JGSDF_Type88_SSM-02.jpg",
  "Type-93 ASM Airborne ALCM": "https://upload.wikimedia.org/wikipedia/commons/2/2d/JASDF_ASM-2_Dummy.JPG",
  "Hyunmoo-5 Heavy Ballistic": "https://upload.wikimedia.org/wikipedia/commons/3/30/%ED%99%94%EB%A0%A5_%EC%9C%A0%EB%8F%84%ED%83%84-%ED%98%84%EB%AC%B4_%287445968002%29.jpg",
  "Hyunmoo-3C LACM": "https://upload.wikimedia.org/wikipedia/commons/9/9e/Hyunmoo-3_missile_carrier.jpg",
  "FC/ASW Supersonic LACM": "https://upload.wikimedia.org/wikipedia/commons/c/c2/Maquette_du_missile_FC_ASW_de_MBDA_au_Salon_du_Bourget_2025.jpg",
  "SPEAR 3 Standoff ALCM": "https://upload.wikimedia.org/wikipedia/commons/9/91/SPEAR3Deployed.jpg",
  "SCALP Naval (MdCN)": "https://upload.wikimedia.org/wikipedia/commons/3/3f/RAF_Museum%2C_Colindale%2C_London_-_DSC06025.JPG",
  "AASM Hammer 1000 Glide Bomb": "https://upload.wikimedia.org/wikipedia/commons/8/8c/Aasm5.jpg",
  "Taurus KEPD 350 (Standalone)": "https://upload.wikimedia.org/wikipedia/commons/8/83/Taurus_ILA2006.JPG",
  "DeepStrike Missile (Standalone)": "https://upload.wikimedia.org/wikipedia/commons/c/c4/Precision_Strike_Missile_(PrSM)_Increment_1_Limited_User_Test.jpg",
  "F-16C/D Fighting Falcon (USA)": "https://upload.wikimedia.org/wikipedia/commons/c/c9/F-16_June_2008.jpg",
  "F-15C/D Eagle": "https://upload.wikimedia.org/wikipedia/commons/a/a6/F-15C_Eagle_from_the_44th_Fighter_Squadron_flies_during_a_routine_training_exercise_April_15%2C_2019.jpg",
  "F-15E Strike Eagle": "https://upload.wikimedia.org/wikipedia/commons/e/e6/F-15E_takes_on_fuel_from_KC-10.jpg",
  "F-15EX Eagle II": "https://upload.wikimedia.org/wikipedia/commons/4/43/F-15EX_Eagle_II.jpg",
  "F/A-18E/F Super Hornet": "https://upload.wikimedia.org/wikipedia/commons/d/de/US_Navy_071203-N-8923M-074_An_F-A-18F_Super_Hornet%2C_from_the_Red_Rippers_of_Strike_Fighter_Squadron_%28VFA%29_11%2C_makes_a_sharp_turn_above_the_flight_deck_aboard_the_Nimitz-class_nuclear-powered_aircraft_carrier_USS_Harry_S._Truman.jpg",
  "A-10C Warthog": "https://upload.wikimedia.org/wikipedia/commons/8/80/Fairchild_Republic_A-10_Thunderbolt_II_-_32156159151.jpg",
  "B-1B Lancer": "https://upload.wikimedia.org/wikipedia/commons/7/7d/B-1B_air_refueling.jpg",
  "B-2A Spirit": "https://upload.wikimedia.org/wikipedia/commons/7/77/RAF_F-35B_integration_flying_training_with_USAF_B-2_30092019_-_4.jpg",
  "B-52H Stratofortress": "https://upload.wikimedia.org/wikipedia/commons/1/16/B-52_Stratofortress_assigned_to_the_307th_Bomb_Wing_%28cropped%29.jpg",
  "Su-34 Fullback": "https://upload.wikimedia.org/wikipedia/commons/7/76/MAKS2015part1-10_%28cropped%29.jpg",
  "MiG-31K Foxhound-D": "https://upload.wikimedia.org/wikipedia/commons/3/38/Russian_Air_Force_Mikoyan-Gurevich_MiG-31P.jpg",
  "Tu-22M3 Backfire": "https://upload.wikimedia.org/wikipedia/commons/0/0c/Tupolev_Tu-22M3M_GEFEST_%2819230388334%29.jpg",
  "Tu-95MS Bear": "https://upload.wikimedia.org/wikipedia/commons/0/02/Tupolev_Tu-95_over_Moscow_Kustov_%28cropped%29.jpg",
  "MiG-29SMT Fulcrum-E": "https://upload.wikimedia.org/wikipedia/commons/0/0c/Russian_Air_Force%2C_747%2C_Mikoyan-Gurevich_MiG-29M2.jpg",
  "MiG-35 Fulcrum-F": "https://upload.wikimedia.org/wikipedia/commons/1/1a/1MiG-35.jpg",
  "Su-27S Flanker-B": "https://upload.wikimedia.org/wikipedia/commons/0/04/Sukhoi_Su-27SKM_at_MAKS-2005_airshow.jpg",
  "Su-30SM Flanker-H": "https://upload.wikimedia.org/wikipedia/commons/7/76/Sukhoi_Su-30SM_in_flight_2014.jpg",
  "MiG-31 Foxhound": "https://upload.wikimedia.org/wikipedia/commons/3/38/Russian_Air_Force_Mikoyan-Gurevich_MiG-31P.jpg",
  "Su-35S Flanker-E": "https://upload.wikimedia.org/wikipedia/commons/e/ec/Russian_Air_Force,_RF-81719,_Sukhoi_Su-35S_(49581740157).jpg",
  "Su-57 Felon": "https://upload.wikimedia.org/wikipedia/commons/0/0e/Sukhoi_Design_Bureau,_054,_Sukhoi_T-50_(Su-57_prototype)_(49581303977).jpg",
  "JH-7A": "https://upload.wikimedia.org/wikipedia/commons/1/18/PLAAF_Xian_JH-7A_at_Chelyabinsk_Shagol_Air_Base.jpg",
  "H-6K Strategic Bomber": "https://upload.wikimedia.org/wikipedia/commons/b/ba/H-6K_20211_20151127.jpg",
  "Heron TP (Luftwaffe UAV)": "https://upload.wikimedia.org/wikipedia/commons/1/19/IAF-Eitan--Independence-Day-2017-Tel-Nof-IZE-099.jpg",
  "JF-17 Thunder Block II": "https://upload.wikimedia.org/wikipedia/commons/1/1b/Pakistan_Air_Force_Chengdu_JF-17_Gu.jpg",
  "Akinci UCAV (PAF)": "https://upload.wikimedia.org/wikipedia/commons/f/f2/Bayraktar_Ak%C4%B1nc%C4%B1_of_the_Azerbaijani_Air_Force.jpg",
  "Bayraktar TB2 (UCAV)": "https://upload.wikimedia.org/wikipedia/commons/4/4d/Bayraktar_TB2_Runway.jpg",
  "Mirage III (PAF)": "https://upload.wikimedia.org/wikipedia/commons/e/e6/Two_Mirage_III_of_the_Royal_Australian_Air_Force_1.JPEG",
  "Mirage 5 (PAF)": "https://upload.wikimedia.org/wikipedia/commons/a/a2/Chile_Air_Force_Dassault_%28SABCA%29_Mirage_5MA_Elkan_Lofting-2.jpg",
  "F-35A Lightning II (USA)": "https://upload.wikimedia.org/wikipedia/commons/6/61/F-35A_flight_%28cropped%29.jpg",
  "F-22 Raptor (USA)": "https://upload.wikimedia.org/wikipedia/commons/1/1e/F-22_Raptor_edit1_%28cropped%29.jpg",
  "J-20 Mighty Dragon": "https://upload.wikimedia.org/wikipedia/commons/7/73/J-20_at_CCAS2022_%2820220827103424%29.jpg",
  "J-16": "https://upload.wikimedia.org/wikipedia/commons/f/f8/PLAAF_J-16_-_2.jpg",
  "MQ-9 Reaper (India)": "https://upload.wikimedia.org/wikipedia/commons/1/12/MQ-9_Reaper_UAV_%28cropped%29.jpg",
  "IAI Heron TP (India)": "https://upload.wikimedia.org/wikipedia/commons/1/19/IAF-Eitan--Independence-Day-2017-Tel-Nof-IZE-099.jpg",
  "IAI Harop (India)": "https://upload.wikimedia.org/wikipedia/commons/4/41/IAI_Harop_PAS_2013_01.jpg",
  "Divyastra Mk-1": "https://upload.wikimedia.org/wikipedia/commons/7/71/Agni-V_ICBM_MIRVed_test_launch_on_11_March_2024.jpg",
  "HQ-17AE SAM Battery": "https://upload.wikimedia.org/wikipedia/commons/e/ec/SPZR_Poprad_Bull_Run-12_%28cropped%29.jpg",
  "Sky Sabre (CAMM-ER) Battery": "https://upload.wikimedia.org/wikipedia/commons/a/a8/Land_Ceptor_at_DVD_2018_2.jpg",
  "Land Ceptor CAMM Battery": "https://upload.wikimedia.org/wikipedia/commons/a/a8/Land_Ceptor_at_DVD_2018_2.jpg",
  "Ghauri-II": "https://upload.wikimedia.org/wikipedia/commons/8/81/Ghauri_missile_mockup.jpeg",
  "H-6K (Educational Reference)": "https://upload.wikimedia.org/wikipedia/commons/b/ba/H-6K_20211_20151127.jpg",
  "Generic Loitering Munition": "https://upload.wikimedia.org/wikipedia/commons/8/8f/ZALA_Lancet_1.jpg",
  "Nasr (Hatf-IX)": "https://upload.wikimedia.org/wikipedia/commons/5/5b/Nasr_missile_at_parade.webp",
  "Ababeel": "/images/equipment/ballistic_missile.png",
  "Ghaznavi": "/images/equipment/ballistic_missile.png",
  "Fateh-1": "https://upload.wikimedia.org/wikipedia/commons/9/9e/Pakistani_Fatah-1-and-fatah-2_MLRS.jpg",
  "Fateh-2": "https://upload.wikimedia.org/wikipedia/commons/9/9e/Pakistani_Fatah-1-and-fatah-2_MLRS.jpg",
  "Agni-P (Agni-Prime)": "https://upload.wikimedia.org/wikipedia/commons/6/6c/Agni-P_missile_ready_for_launch.jpg",
  "Pralay": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Launch_of_indigenously_developed_surface-to-surface_missile_Pralay_%28cropped%29.jpg",
  "Mirage 2000I": "https://upload.wikimedia.org/wikipedia/commons/c/c5/Mirage_2000C_in-flight_2_%28cropped%29.jpg",
  "Tapas BH-201": "https://upload.wikimedia.org/wikipedia/commons/1/11/Rustom_flight_2_%28cropped%29.jpg",
  "Archer ALFA": "/images/equipment/military_uav.png",
  "Pinaka Guided Rocket": "https://upload.wikimedia.org/wikipedia/commons/1/1c/DRDO_successfully_test_fired_the_Guided_PINAKA_on_March_11,_2019.jpg",
  "ALS-50 Loitering Munition": "https://upload.wikimedia.org/wikipedia/commons/8/8f/ZALA_Lancet_1.jpg",
  "Agni-I": "https://upload.wikimedia.org/wikipedia/commons/6/60/Agni-I_missile_test_on_13_July_2012_%28cropped%29.jpg",
  "Eurofighter Typhoon FGR4 (RAF)": "https://upload.wikimedia.org/wikipedia/commons/3/3c/RAF_Eurofighter_EF-2000_Typhoon_F2_Lofting-1.jpg",
  "F-35B Lightning II (RAF)": "https://upload.wikimedia.org/wikipedia/commons/6/61/F-35A_flight_(cropped).jpg",
  "MQ-9A Reaper (RAF)": "https://upload.wikimedia.org/wikipedia/commons/1/12/MQ-9_Reaper_UAV_%28cropped%29.jpg",
  "Rafale C (French Air Force)": "https://upload.wikimedia.org/wikipedia/commons/6/64/Rafale_-_RIAT_2009_(3751416421).jpg",
  "Rafale M (French Navy)": "https://upload.wikimedia.org/wikipedia/commons/6/64/Rafale_-_RIAT_2009_(3751416421).jpg",
  "Mirage 2000-5F (French Air Force)": "https://upload.wikimedia.org/wikipedia/commons/c/c5/Mirage_2000C_in-flight_2_(cropped).jpg",
  "nEUROn UCAV (Stealth Drone)": "https://upload.wikimedia.org/wikipedia/commons/3/3e/NEUROn_-_Dassault_Aviation_-_Démonstrateur_de_drone_de_combat_(cropped).jpeg",
  "Eurofighter Typhoon (Luftwaffe)": "https://upload.wikimedia.org/wikipedia/commons/3/3c/RAF_Eurofighter_EF-2000_Typhoon_F2_Lofting-1.jpg",
  "Panavia Tornado IDS (Luftwaffe)": "https://upload.wikimedia.org/wikipedia/commons/2/25/RAF_Tornado_GR4_MOD_45155233.jpg",
  "Ra'ad-II ALCM": "https://upload.wikimedia.org/wikipedia/commons/3/32/Pakistan_air_force_1.png",
  "Generic Hypersonic Cruise Missile": "https://upload.wikimedia.org/wikipedia/commons/f/f6/Zirkon_03.12.2024.jpg",
  "Generic Hypersonic Glide Vehicle": "https://upload.wikimedia.org/wikipedia/commons/7/72/DF-17_Missile_20221020.jpg",
  "Harbah": "https://upload.wikimedia.org/wikipedia/commons/e/ec/Babur_Cruise_Missle_at_Ideas_2008.jpg",
  "Taimoor ALCM": "https://upload.wikimedia.org/wikipedia/commons/9/97/4_Babur_Cruise_Missles_on_a_Truck_at_IDEAS_2008.jpg",
  "HQ-9P HIMADS Regiment": "https://upload.wikimedia.org/wikipedia/commons/d/d0/Chinese_HQ-9_launcher.jpg",
  "Shahpar-2": "https://upload.wikimedia.org/wikipedia/commons/6/6f/GIDS_Shahpar_2_Drone.jpg",
  "Burraq UAV": "https://upload.wikimedia.org/wikipedia/commons/5/5f/NESCOM_Burraq_UAV.jpg",
  "CM-302": "https://upload.wikimedia.org/wikipedia/commons/c/cd/YJ-12_cropped.jpg",
  "C-802AK": "https://upload.wikimedia.org/wikipedia/commons/c/c6/C-802_(top)_and_C-705_(bottom)_missiles_being_launched-1024x576.png",
  "C-705KD": "https://upload.wikimedia.org/wikipedia/commons/c/c6/C-802_(top)_and_C-705_(bottom)_missiles_being_launched-1024x576.png",
  "BrahMos Land-Attack": "https://upload.wikimedia.org/wikipedia/commons/5/55/Brahmos_Block_III.jpg",
  "Nirbhay": "https://upload.wikimedia.org/wikipedia/commons/e/e8/Nirbhay_cruise_missile.jpg",
  "Su-30MKI": "https://upload.wikimedia.org/wikipedia/commons/f/ff/NellisIAFSu30MKI.jpg",
  "Rafale": "https://upload.wikimedia.org/wikipedia/commons/0/07/Dassault_Rafale_of_Indian_Air_Force_squadron_101_landing_in_Hasimara.jpg",
  "DF-100 Supersonic LACM": "https://upload.wikimedia.org/wikipedia/commons/e/ef/CJ-10_Cruise_missile_20170919.jpg",
  "J-8II": "https://upload.wikimedia.org/wikipedia/commons/5/59/20220804_J-8II_Fighter_on_Display_at_Jinming_Service_Area_02_(cropped).jpg",
  "J-11B": "https://upload.wikimedia.org/wikipedia/commons/d/dc/J-11B_at_China's_Air_Force_Aviation_Open_Day_20250921.jpg",
  "J-15 Flying Shark": "https://upload.wikimedia.org/wikipedia/commons/1/11/PLAN_Shenyang_J-15_carrier-based_fighter_aircraft_20250608_-_1.jpg",
  "J-35": "https://upload.wikimedia.org/wikipedia/commons/9/94/J-35A.jpg",
  "Su-30MKK Flanker-G": "https://upload.wikimedia.org/wikipedia/commons/7/72/PLAAF_Sukhoi_Su-30_at_Lipetsk-2_(modified).jpg",
  "F-15J Eagle (JASDF)": "https://upload.wikimedia.org/wikipedia/commons/5/53/JASDF_F-15_at_Chitose_Air_Base.jpg",
  "F-15DJ Eagle (JASDF Trainer)": "https://upload.wikimedia.org/wikipedia/commons/5/53/JASDF_F-15_at_Chitose_Air_Base.jpg",
  "KF-5E/F Tiger II (ROKAF)": "https://upload.wikimedia.org/wikipedia/commons/c/c3/F-5E_Tiger_II_in_flight.jpg",
  "FA-50 Block 20 / FA-50PL": "https://upload.wikimedia.org/wikipedia/commons/5/54/FA-50_Fighting_Eagle_Test_Flight.jpg",
  "F-2A Viper Zero (JASDF)": "https://upload.wikimedia.org/wikipedia/commons/3/3d/JASDF_Mitsubishi_F-2A_over_the_Pacific_Ocean.jpg",
  "RQ-4B Global Hawk (JASDF)": "https://upload.wikimedia.org/wikipedia/commons/9/9e/RQ-4_Global_Hawk_in_flight.jpg",
  "KF-21 Boramae (ROKAF)": "https://upload.wikimedia.org/wikipedia/commons/e/e5/2024-09-25_KF-21_Boramae_001.jpg",
  "RQ-4 Block 30 Global Hawk (ROKAF)": "https://upload.wikimedia.org/wikipedia/commons/9/9e/RQ-4_Global_Hawk_in_flight.jpg",
  "F-16 Block 52+": "https://upload.wikimedia.org/wikipedia/commons/c/c9/F-16_June_2008.jpg",
  "Su-35S Flanker-E (Chinese)": "https://upload.wikimedia.org/wikipedia/commons/e/ec/Russian_Air_Force,_RF-81719,_Sukhoi_Su-35S_(49581740157).jpg",
  "Su-27SK Flanker (Chinese)": "https://upload.wikimedia.org/wikipedia/commons/0/04/Sukhoi_Su-27SKM_at_MAKS-2005_airshow.jpg",
  "H-6N": "https://upload.wikimedia.org/wikipedia/commons/b/ba/H-6K_20211_20151127.jpg",
  "F-35A Lightning II (ROKAF)": "https://upload.wikimedia.org/wikipedia/commons/6/61/F-35A_flight_(cropped).jpg",
  "F-35A Lightning II (JASDF)": "https://upload.wikimedia.org/wikipedia/commons/6/61/F-35A_flight_(cropped).jpg",
  "F-35B Lightning II (JASDF STOVL)": "https://upload.wikimedia.org/wikipedia/commons/6/61/F-35A_flight_(cropped).jpg",
  "F-15K Slam Eagle (ROKAF)": "https://upload.wikimedia.org/wikipedia/commons/e/e6/F-15E_takes_on_fuel_from_KC-10.jpg",
  "Protector RG Mk1 (GA-ASI MQ-9B)": "https://upload.wikimedia.org/wikipedia/commons/1/12/MQ-9_Reaper_UAV_(cropped).jpg",
  "Peacekeeper (Agniveg)": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Advanced_Agni_Missile.jpg"
};

// Fallback placeholder
const FALLBACK_IMAGE = '/fallback-military.svg';

/**
 * Get the image URL for any equipment by name.
 */
export function getEquipmentImageUrl(name: string, category?: string): string {
  if (WIKI_IMAGES[name]) {
    return WIKI_IMAGES[name];
  }

  // General fallback category based (local generated backups if wiki fails)
  const CATEGORY_FALLBACKS: Record<string, string> = {
    'LONG_RANGE': '/images/equipment/sam_long_range.png',
    'MEDIUM_RANGE': '/images/equipment/sam_medium_range.png',
    'SHORT_RANGE': '/images/equipment/sam_short_range.png',
    'VERY_SHORT_RANGE': '/images/equipment/manpads_vshorad.png',
    'RADAR': '/images/equipment/military_radar.png',
    'FIGHTER': '/images/equipment/fighter_jet.png',
    'BALLISTIC': '/images/equipment/ballistic_missile.png',
    'CRUISE': '/images/equipment/cruise_missile.png',
    'UAV': '/images/equipment/military_uav.png',
    'LOITERING_MUNITION': '/images/equipment/loitering_munition.png',
    'TACTICAL_MISSILE': '/images/equipment/tactical_missile.png',
    'SWARM': '/images/equipment/drone_swarm.png',
  };

  if (category) {
    const normalized = category.replace(/\s+/g, '_').toUpperCase();
    if (CATEGORY_FALLBACKS[normalized]) {
      return CATEGORY_FALLBACKS[normalized];
    }
  }

  return FALLBACK_IMAGE;
}
