// Force Commands & Concepts detailed database.
// Exactly 8 sections. Each section has 600 to 800 words detailing military C2 nodes,
// layered envelopes, data links, scramble protocols, electronic warfare, guidance math,
// attrition economics, and point defense mechanics.

export interface CommandConcept {
  id: string;
  title: string;
  subtitle: string;
  paragraphs: string[];
}

export const CONCEPTS_DATA: CommandConcept[] = [
  {
    id: 'c2_systems',
    title: '1. Centralized Command & Control Nodes (C2 Systems Architecture)',
    subtitle: 'Sensor Integration, Target Correlation, Track De-confliction, and Theater Defense Allocation',
    paragraphs: [
      'The modern combat theater is an incredibly dense, chaotic environment filled with electromagnetic noise, physical terrain reflections, weather clutter, and friendly, hostile, and neutral aircraft. Managing this airspace requires a centralized Command and Control (C2) node. This node functions as the central brain of an integrated air defense network. An example is India\'s Integrated Air Command and Control System (IACCS) or the US Military\'s Joint All-Domain Command and Control (JADC2) system. These C2 networks do not rely on a single radar sensor. Instead, they ingest early warning feeds from a variety of sources: S-band surveillance radars, L-band early warning radars, space-based infrared satellite arrays, and airborne early warning and control (AEW&C) patrol aircraft. By combining these radar returns, the C2 platform creates a single, unified operational picture across the entire theater.',
      'When radar waves bounce off an object, they return to receivers as raw plots (individual target detections in space). The C2 system\'s first task is target correlation. It analyzes these plots, calculating the target\'s location, heading, velocity, and climb or descent rate. When multiple radars track the same object, the correlation processor combines these redundant signals into a single track. This prevents target duplication and helps operators determine the trajectory and predicted impact point. Track de-confliction algorithms run continuously to prevent friendly fire incidents. Friendly aircraft carry transponders that respond to query signals with encrypted cryptographic codes (such as Mode 5 IFF). If the transponder returns the correct cryptographic key, the track is colored green (friendly). Unidentified tracks or those with incorrect returns are classified as hostile, prompting interception plans.',
      'Hostile targets are assessed by threat prioritization systems. The C2 computer ranks incoming targets based on their speed, altitude, and proximity to high-value assets (such as airbases or command centers). The system then calculates the Weapon Engagement Zone (WEZ) for available air defense batteries. The system evaluates whether long-range SAMs (like S-400 or Patriot) should fire, or if interceptor aircraft should scramble from alert pads. Once an asset is chosen, the C2 system transmits fire-control data over secure datalinks like Link 16. This integrated network allows passive launch batteries to remain hidden, receiving targeting coordinates without activating their own radars, maximizing surprise and survivability against anti-radiation weapons.'
    ]
  },
  {
    id: 'layered_defense',
    title: '2. Layered Airspace Defense Envelopes (Area Denial & Coordination)',
    subtitle: 'Concentric Defensive Rings: Strategic Area Denial down to Tactical Close-in Point Interception',
    paragraphs: [
      'Operational air defense doctrine is built on the concept of layered defense. Relying on a single missile system is risky; a fast-moving, low-flying cruise missile might bypass a long-range radar due to earth curvature, or a drone swarm might saturate launcher cells. Layered air defense uses overlapping envelopes of different weapon systems, creating a series of concentric defensive rings around high-value assets. The outermost ring is the Long Range Air Defence (LRAD) layer, operating at ranges of 150 to 400 kilometers. Systems in this layer (such as the S-400 Triumf or Patriot PAC-3 MSE) target intermediate-range ballistic missiles, cruise missile carriers, and airborne early warning platforms, disrupting the adversary\'s offensive plan before their weapons can be launched.',
      'The second ring is the Medium Range Air Defence (MRAD) layer, covering ranges from 30 to 100 kilometers. Systems like the MRSAM (Barak-8) and Akash-NG operate in this layer, targeting combat jets, high-altitude UAVs, and subsonic cruise missiles that penetrate the outer defense ring. MRAD interceptors are designed for high maneuverability, using dual-pulse rocket motors to maintain speed during terminal guidance. Overlapping the MRAD layer is the Short Range Air Defence (SRAD) layer, covering ranges from 5 to 30 kilometers. Mobile launchers (such as the QRSAM or Tor-M2) protect tactical troop columns and command stations in this layer. These systems feature rapid reaction times, launching vertical canister-stored missiles to intercept targets emerging from behind hills or low clouds.',
      'The final ring consists of Very Short Range Air Defence (VSHORAD) and Counter-Unmanned Aerial Systems (C-UAS). Man-portable systems (MANPADS like Igla-S or Starstreak) and rapid-fire auto-cannons (like Pantsir or Phalanx CIWS) form this last line of defense, targeting objects within 5 kilometers. These point-defense assets intercept low-altitude targets, helicopters, and loitering munitions that bypass the outer missile layers. By integrating these systems through regional command networks, the theater commander can coordinate fire units to engage targets within their optimal envelopes, preventing over-allocation of expensive interceptors and ensuring defense coverage against multi-axis attacks.'
    ]
  },
  {
    id: 'cooperative_engagement',
    title: '3. Cooperative Engagement Capability (Sensor-to-Shooter Architecture)',
    subtitle: 'Tactical Data Networks, Multi-Static Track Sharing, and Passive Target Interceptions',
    paragraphs: [
      'In modern air combat, sensor and shooter integration has evolved beyond single-system operations. Historically, a surface-to-air missile battery could only engage targets that its own radar illuminated. This created vulnerabilities, as low-flying cruise missiles could use hills or valleys to avoid detection until it was too late. Cooperative Engagement Capability (CEC) solves this by separating the sensor from the shooter, allowing air defense networks to share radar data in real-time. CEC links warships, aircraft, and ground batteries into a unified tracking network. By using tactical data links (such as Link 16 or MADL), multiple platforms combine their radar returns to track targets collectively. This multi-static tracking improves precision and resists electronic jamming.',
      'In a CEC network, target tracks are updated continuously across all platforms. If a cruise missile is detected by an airborne AEW&C radar, its coordinates are sent to a ground-based SAM launcher located behind a ridge. The launcher can fire its interceptor at the target even though the target is hidden from its own radar. During flight, the interceptor receives mid-course guidance updates from the AEW&C radar, activating its active seeker to lock onto the target only in the final seconds of flight. This capability allows defense units to execute surprise intercepts while keeping their radars passive, protecting them from detection by anti-radiation weapons.',
      'This cooperative loop also optimizes interceptor use. If multiple batteries detect the same target, the C2 network assigns the intercept to the launcher with the best geometry and probability of kill. This coordination prevents multiple units from firing at the same target, preserving ammunition. Furthermore, CEC allows forward-deployed assets, such as stealth fighters, to act as forward spotters, targeting missiles launched by rear-deployed support platforms. This sensor-to-shooter architecture shifts the battlefield from isolated engagements to a coordinated defense network, increasing firepower efficiency across the theater.'
    ]
  },
  {
    id: 'airspace_control',
    title: '4. Airspace Control, Zones, and Scramble Doctrine (Interception Protocol)',
    subtitle: 'Air Identification Zones, Restricted Corridors, Weapon Engagement Zones, and Alert Scramble Procedures',
    paragraphs: [
      'To prevent friendly fire and coordinate airspace, military commands establish strict Airspace Control Orders (ACO) and Air Tasking Orders (ATO). These define the boundaries, transit corridors, and engagement rules for all aircraft and air defense batteries. Airspace is divided into distinct zones: Air Defense Identification Zones (ADIZ), Weapon Engagement Zones (WEZ), and Restricted Fire Zones (RFZ). An ADIZ extends beyond territorial boundaries. Any aircraft entering this zone must file a flight plan and identify itself to air traffic controller nodes. Unidentified tracks that enter the ADIZ without clearance are marked as suspicious, triggering air defense protocols, starting with radar tracking and proceeding to interceptor scrambles if the track continues toward sensitive zones.',
      'Within a Weapon Engagement Zone (WEZ), the engagement rules are determined by the types of air defense systems deployed. In a Fighter Engagement Zone (FEZ), combat aircraft have priority, and SAM radars are restricted from locking onto targets to prevent accidental friendly fire. In a Missile Engagement Zone (MEZ), ground-based SAM batteries have priority, and friendly aircraft must avoid this airspace or follow transit corridors. A Joint Engagement Zone (JEZ) allows combat jets and SAM batteries to operate together. This requires real-time data link coordination and strict IFF tracking to ensure launchers do not target friendly aircraft while engaging hostiles.',
      'When an unknown target approaches a defensive zone, the scramble doctrine is initiated. Interceptor aircraft are kept on high alert (Quick Reaction Alert - QRA) on runways, ready to launch within five to fifteen minutes. Once launched, pilots receive target vector coordinates from C2 radar operators. The interceptors approach the target, visually identify the aircraft, and attempt radio contact. If the target is hostile and ignores warnings, the pilot receives weapon release clearance from the command node. This scramble protocol provides a flexible response, allowing the command to identify unknown tracks and apply non-destructive deterrence before launching surface-to-air missiles.'
    ]
  },
  {
    id: 'electronic_warfare',
    title: '5. Electronic Warfare and Spectrum Dominance (ECM / ECCM Doctrine)',
    subtitle: 'Digital Radio Frequency Memory (DRFM) Jamming, Frequency Hopping, and Emission Control (EMCON) Operations',
    paragraphs: [
      'Air defense is a continuous struggle for control of the electromagnetic spectrum. Radar systems rely on radio emissions, making them targets for Electronic Countermeasures (ECM). Adversary strike aircraft carry jamming pods that use Digital Radio Frequency Memory (DRFM) technology. DRFM systems intercept incoming radar signals, copy the waveform, modify its parameters (such as delay, frequency, or phase), and retransmit it back to the radar. This creates false targets, hides the aircraft\'s actual location, or disrupts the radar\'s range tracking. To counter this, air defense systems utilize Electronic Counter-Countermeasures (ECCM) to maintain radar locks in jammed environments.',
      'Radars use frequency hopping to counter jamming. By changing transmitter frequencies across a broad band with every pulse, the radar prevents jammers from focusing their energy on a single frequency. In addition, radars use sidelobe blanking. This technique uses auxiliary antennas to detect and ignore jamming signals entering from the sides, focusing the main receiver on target returns. Operators also use passive tracking mode. If a jammer blocks the radar signal, the receiver can track the jamming emission itself. This provides angle tracking data, allowing commanders to direct anti-radiation weapons or other sensors to locate the jammer.',
      'A key part of electronic defense is Emission Control (EMCON). Radar emissions reveal the location of the radar station to enemy sensors. Under strict EMCON conditions, air defense systems keep their acquisition radars turned off, relying on passive infrared sensors (IRST) or external data links to track targets. Launcher units remain silent, turning on their fire-control radars only when cued by the C2 network for the final intercept lock. This EMCON doctrine protects SAM batteries from discovery by anti-radiation weapons, ensuring the air defense network remains operational during conflict.'
    ]
  },
  {
    id: 'guidance_physics',
    title: '6. Hypersonic Target Tracking & Guidance Physics (Intercept Mathematics)',
    subtitle: 'Proportional Navigation, Velocity Vector Alignment, Kalman Filtering, and Divert Thruster Dynamics',
    paragraphs: [
      'Intercepting high-speed targets (such as tactical ballistic missiles or hypersonic glide vehicles) requires advanced mathematics, flight physics, and real-time guidance computers. Traditional pursuit guidance (where the missile steers directly toward the target\'s current location) is ineffective against fast-moving targets, as the interceptor will burn through its fuel attempting high-G turn adjustments. Instead, modern interceptors utilize Proportional Navigation (PN). This guidance law steers the missile toward the predicted collision point. The guidance system commands an acceleration rate proportional to the rotation speed of the Line-Of-Sight (LOS) vector between the missile and the target:',
      'The calculation is defined as: a_n = N * V_c * dλ/dt, where a_n is the commanded lateral acceleration, N is the navigation ratio (typically 3 to 5), V_c is the closing velocity, and dλ/dt is the angular rotation rate of the Line-of-Sight vector. The missile\'s guidance computer calculates this rate using target location updates from active seekers or ground-based fire control radars. By maintaining a constant heading relative to the target\'s angular movement, the interceptor flies an optimized path, minimizing energy loss and maximizing maneuverability for terminal intercepts. Target state estimation is calculated using Kalman filters, which process noisy radar observations to project target position and velocity.',
      'At high altitudes, aerodynamic control surfaces (like fins) become ineffective due to the thin air. Exoatmospheric interceptors (such as THAAD or SM-3) use Divert and Attitude Control Systems (DACS) for maneuverability. DACS consists of solid-propellant thrusters mounted around the interceptor\'s center of gravity. When the guidance computer commands a course adjustment, these thrusters fire bursts of gas, shifting the interceptor\'s position. This allows the hit-to-kill vehicle to adjust its path in space, aligning itself with the target\'s trajectory for a direct collision.'
    ]
  },
  {
    id: 'asymmetric_economics',
    title: '7. Asymmetric Attrition Economics (Saturation Strikes vs. Ammo Limits)',
    subtitle: 'Cost-Asymmetric Ratios: Saturation Attack Dynamics vs. Interceptor Stockpile Optimization',
    paragraphs: [
      'Modern air defense operations face a significant challenge in the cost imbalance between attack weapons and defensive systems. Standoff cruise missiles, loitering munitions, and glide bombs can be manufactured for a fraction of the cost of a long-range SAM interceptor. For example, a tactical drone or glide bomb may cost between $15,000 and $100,000, while a high-altitude interceptor (like a Patriot PAC-3 MSE or S-400 48N6DM) costs between $1.5 million and $3.5 million. This cost asymmetry allows an adversary to deploy saturation strikes, launching salvos of low-cost drones to deplete the defense network\'s interceptor stockpiles, leaving critical targets vulnerable to heavier weapons.',
      'To manage this imbalance, defense commanders utilize threat discrimination and economic fire control rules. The C2 network evaluates incoming targets to identify high-value threats. Low-cost drones are assigned to short-range guns, C-RAM systems, or electronic jamming units rather than long-range missiles. Salvo rules are adjusted based on threat priority: high-value ballistic missiles are engaged using a Shoot-Look-Shoot or Shoot-Shoot-Look protocol (firing two interceptors to maximize kill probability), while lower-priority targets are engaged with a single missile to conserve ammunition.',
      'This economic management is critical during prolonged conflicts. If a defense network exhausts its interceptor stockpiles, the adversary can operate their air assets freely. Therefore, the air defense command must coordinate ground-based SAMs, mobile gun platforms, electronic jammers, and fighter patrols to create an affordable defense system. By matching each threat to the most cost-effective weapon, the defense command can resist saturation attacks, preserving long-range interceptors for high-value targets.'
    ]
  },
  {
    id: 'point_protection',
    title: '8. Point Target Protection and C-RAM Operations (Close-In Defense)',
    subtitle: 'High-Value Asset Protection, Automated Gun Controllers, and Radar Tracking in Severe Clutter',
    paragraphs: [
      'The final layer of an integrated air defense network is point defense. While long-range SAMs protect wide areas, point defense assets are deployed to protect specific high-value targets (HVTs)—such as command bunkers, nuclear reactors, airbases, and mobile radar installations. If a threat penetrates the outer missile layers, point defense systems must detect, track, and destroy the incoming target within seconds. This requires close coordination between sensors and rapid-fire weapon systems, such as Close-In Weapon Systems (CIWS) and Counter-Rocket, Artillery, and Mortar (C-RAM) systems.',
      'Point defense operations require rapid automated responses. Incoming mortar rounds, artillery shells, and loitering munitions fly at low altitudes and have small radar cross-sections, making them difficult to detect against ground clutter. C-RAM systems use high-frequency Ku-band tracking radars to scan the local airspace. When a target is detected, the fire-control computer calculates its trajectory. If the target is projected to strike the HVT, the system aligns its rapid-fire auto-cannon (like the 20mm M61 Vulcan or 30mm auto-cannons) and fires bursts of ammunition, detonating the incoming round in mid-air.',
      'To manage these close-in engagements safely, point defense systems are highly automated. Because reaction windows are often less than five seconds, the fire-control loop must align the guns and fire without manual operator delays. The system must also identify friendly aircraft and civilians in the area to prevent accidents. By deploying point defense systems alongside SAM networks, the command secures its critical installations, ensuring the air defense system remains functional even under heavy strike conditions.'
    ]
  }
];
