// ============================================
// IADES - Database Seed Data
// ============================================
// All data is from publicly available sources.
// Values are educational estimates where exact data is unavailable.

import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding IADES database...\n');

  // ---- Seed Admin User ----
  const adminPassword = await bcrypt.hash('admin123', 12);
  const demoPassword = await bcrypt.hash('demo123', 12);

  const admin = await prisma.user.upsert({
    where: { email: 'admin@iades.edu' },
    update: {},
    create: {
      email: 'admin@iades.edu',
      name: 'IADES Admin',
      passwordHash: adminPassword,
      role: 'ADMIN',
    },
  });

  const demoUser = await prisma.user.upsert({
    where: { email: 'demo@iades.edu' },
    update: {},
    create: {
      email: 'demo@iades.edu',
      name: 'Demo User',
      passwordHash: demoPassword,
      role: 'PLAYER',
    },
  });

  console.log('✅ Users seeded');

  // ---- Seed Air Defence Systems ----
  const systems = [
    // LONG RANGE
    {
      name: 'S-400 Triumf',
      countryOfOrigin: 'Russia',
      category: 'LONG_RANGE' as const,
      minRange: 2,
      maxRange: 400,
      minAltitude: 10,
      maxAltitude: 30000,
      radarType: '91N6E Big Bird + 92N6E Gravestone',
      missileType: '48N6E3 / 40N6E',
      mobilityClass: 'SEMI_MOBILE' as const,
      serviceEntryYear: 2007,
      cost: 1090,
      operatingCostPerHour: 5000,
      reloadTime: 15,
      maxSimultaneousTargets: 80,
      accuracy: 0.9,
      interceptorSpeed: 14.0,
      description: 'The S-400 Triumf is a long-range surface-to-air missile system developed by Russia. In the Indian regiment model used here, one regiment has 2 batteries, 16 launchers with 4 missiles each, 64 ready missiles, 2 engagement radars, 1 surveillance radar, and an estimated regiment cost of $1.09 billion.',
      isIndian: false,
    },
    {
      name: 'S-400 (Indian Configuration)',
      countryOfOrigin: 'Russia / India',
      category: 'LONG_RANGE' as const,
      minRange: 2,
      maxRange: 400,
      minAltitude: 10,
      maxAltitude: 30000,
      radarType: '91N6E Big Bird + 92N6E Gravestone',
      missileType: '48N6E3 / 40N6E',
      mobilityClass: 'SEMI_MOBILE' as const,
      serviceEntryYear: 2021,
      cost: 1090,
      operatingCostPerHour: 5200,
      reloadTime: 15,
      maxSimultaneousTargets: 80,
      accuracy: 0.9,
      interceptorSpeed: 14.0,
      description: 'India procured five S-400 regiments from Russia for approximately $5.43 billion. This model uses a per-regiment structure of 2 batteries, 16 launchers, 4 missiles per launcher, 64 ready missiles, 2 engagement radars, 1 surveillance radar, and an estimated $1.09 billion cost per regiment.',
      isIndian: true,
    },
    // MEDIUM RANGE
    {
      name: 'MRSAM / Barak-8',
      countryOfOrigin: 'India / Israel',
      category: 'MEDIUM_RANGE' as const,
      minRange: 0.5,
      maxRange: 70,
      minAltitude: 15,
      maxAltitude: 16000,
      radarType: 'MF-STAR AESA Radar',
      missileType: 'Barak-8 (LRSAM/MRSAM)',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 2017,
      cost: 500,
      operatingCostPerHour: 2500,
      reloadTime: 8,
      maxSimultaneousTargets: 24,
      accuracy: 0.85,
      interceptorSpeed: 2.0,
      description: 'The Medium Range Surface-to-Air Missile (MRSAM), also called Barak-8, is jointly developed by India (DRDO) and Israel (IAI). This regiment model uses 4 firing units, 12 launchers, 8 canisterized missiles per launcher, 96 ready missiles, 4 radars, and an estimated $500 million cost.',
      isIndian: true,
    },
    {
      name: 'Akash',
      countryOfOrigin: 'India',
      category: 'MEDIUM_RANGE' as const,
      minRange: 3,
      maxRange: 30,
      minAltitude: 30,
      maxAltitude: 18000,
      radarType: 'Rajendra 3D Passive Electronically Scanned Array',
      missileType: 'Akash SAM',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 2014,
      cost: 350,
      operatingCostPerHour: 800,
      reloadTime: 5,
      maxSimultaneousTargets: 4,
      accuracy: 0.75,
      interceptorSpeed: 2.5,
      description: 'Akash is an Indian medium-range surface-to-air missile system developed by DRDO. This regiment model uses 4 batteries, 16 launchers, 3 missiles per launcher, 48 ready missiles, 4 Rajendra radars, and an estimated $350 million cost.',
      isIndian: true,
    },
    {
      name: 'Akash-NG',
      countryOfOrigin: 'India',
      category: 'MEDIUM_RANGE' as const,
      minRange: 5,
      maxRange: 80,
      minAltitude: 30,
      maxAltitude: 20000,
      radarType: 'Active Electronically Scanned Array',
      missileType: 'Akash-NG SAM',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 2025,
      cost: 480,
      operatingCostPerHour: 1200,
      reloadTime: 5,
      maxSimultaneousTargets: 8,
      accuracy: 0.85,
      interceptorSpeed: 3.5,
      description: 'Akash-NG (New Generation) is an upgraded version of the Akash missile system with improved range, speed, and accuracy. This estimated future regiment model uses 3 batteries, 12 launchers, 6 missiles per launcher, 72 ready missiles, 3 AESA fire-control radars, 1 surveillance radar, and an estimated $480 million cost.',
      isIndian: true,
    },
    {
      name: 'Akash Prime',
      countryOfOrigin: 'India',
      category: 'MEDIUM_RANGE' as const,
      minRange: 3,
      maxRange: 30,
      minAltitude: 30,
      maxAltitude: 18000,
      radarType: 'Rajendra Mk-II AESA',
      missileType: 'Akash Prime SAM',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 2022,
      cost: 3.2,
      operatingCostPerHour: 900,
      reloadTime: 5,
      maxSimultaneousTargets: 4,
      accuracy: 0.8,
      interceptorSpeed: 2.5,
      description: 'Akash Prime is an improved variant of the Akash SAM with an indigenous active radio frequency seeker for improved accuracy. It features improved performance at low altitudes and enhanced electronic counter-countermeasures.',
      isIndian: true,
    },
    {
      name: 'Pechora-2M',
      countryOfOrigin: 'Russia',
      category: 'MEDIUM_RANGE' as const,
      minRange: 3,
      maxRange: 35,
      minAltitude: 20,
      maxAltitude: 20000,
      radarType: 'UNV-2M Surveillance Radar',
      missileType: '5V27DE',
      mobilityClass: 'SEMI_MOBILE' as const,
      serviceEntryYear: 2005,
      cost: 15,
      operatingCostPerHour: 1500,
      reloadTime: 10,
      maxSimultaneousTargets: 2,
      accuracy: 0.7,
      interceptorSpeed: 3.5,
      description: 'Pechora-2M is an upgraded version of the S-125 Pechora system. India operates upgraded versions of this medium-range SAM for its air defence role. While aging, it remains an important part of the medium-range layer.',
      isIndian: false,
    },
    {
      name: 'Barak 8 ER',
      countryOfOrigin: 'India / Israel',
      category: 'MEDIUM_RANGE' as const,
      minRange: 0.5,
      maxRange: 150,
      minAltitude: 15,
      maxAltitude: 30000,
      radarType: 'MF-STAR AESA Radar',
      missileType: 'Barak-8 ER (LRSAM/MRSAM)',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 2021,
      cost: 650,
      operatingCostPerHour: 3000,
      reloadTime: 8,
      maxSimultaneousTargets: 24,
      accuracy: 0.88,
      interceptorSpeed: 3.0,
      description: 'The Barak 8 ER (Extended Range) variant extends the operational range to 150km. This regiment model uses 4 firing units, 12 launchers, 8 canisterized missiles per launcher, 96 ready missiles, 4 radars, and an estimated $650 million cost.',
      isIndian: true,
    },
    // SHORT RANGE
    {
      name: 'QRSAM',
      countryOfOrigin: 'India',
      category: 'SHORT_RANGE' as const,
      minRange: 1,
      maxRange: 30,
      minAltitude: 30,
      maxAltitude: 6000,
      radarType: 'Active Array Battery Surveillance Radar',
      missileType: 'QRSAM Missile',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 2024,
      cost: 600,
      operatingCostPerHour: 600,
      reloadTime: 4,
      maxSimultaneousTargets: 4,
      accuracy: 0.82,
      interceptorSpeed: 3.0,
      description: 'Quick Reaction Surface-to-Air Missile (QRSAM) is a short-range air defence system developed by DRDO for the Indian Army. This estimated regiment model uses 3 batteries, 12 launchers, 6 missiles per launcher, 72 ready missiles, 3 AESA radars, 1 surveillance radar, and an estimated $600 million cost.',
      isIndian: true,
    },
    {
      name: 'SPYDER',
      countryOfOrigin: 'Israel',
      category: 'SHORT_RANGE' as const,
      minRange: 1,
      maxRange: 50,
      minAltitude: 20,
      maxAltitude: 16000,
      radarType: 'EL/M-2106 ATAR 3D Radar',
      missileType: 'Derby / Python-5',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 2012,
      cost: 50,
      operatingCostPerHour: 1200,
      reloadTime: 6,
      maxSimultaneousTargets: 20,
      accuracy: 0.82,
      interceptorSpeed: 4.0,
      description: 'SPYDER is a quick-reaction, low-level surface-to-air missile system developed by Rafael. This battery model uses 6 launchers, 4 missiles per launcher, 24 ready missiles, 1 radar, 1 command vehicle, and an estimated $50 million cost.',
      isIndian: false,
    },
    {
      name: 'OSA-AKM',
      countryOfOrigin: 'Russia',
      category: 'SHORT_RANGE' as const,
      minRange: 1.5,
      maxRange: 15,
      minAltitude: 25,
      maxAltitude: 5000,
      radarType: 'Land Roll Radar',
      missileType: '9M33M3',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 1980,
      cost: 5,
      operatingCostPerHour: 400,
      reloadTime: 12,
      maxSimultaneousTargets: 2,
      accuracy: 0.65,
      interceptorSpeed: 2.0,
      description: 'OSA-AKM (SA-8 Gecko) is a Soviet-era mobile short-range SAM system in service with the Indian Army Air Defence. While older, it provides point defence capability for mobile army formations.',
      isIndian: false,
    },
    {
      name: 'Strela-10M3',
      countryOfOrigin: 'Russia',
      category: 'SHORT_RANGE' as const,
      minRange: 0.8,
      maxRange: 5,
      minAltitude: 10,
      maxAltitude: 3500,
      radarType: 'Passive IR/UV Detection',
      missileType: '9M333',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 1989,
      cost: 2,
      operatingCostPerHour: 200,
      reloadTime: 6,
      maxSimultaneousTargets: 1,
      accuracy: 0.6,
      interceptorSpeed: 1.8,
      description: 'Strela-10M3 (SA-13 Gopher) is a short-range infrared-guided SAM used by the Indian Army Air Defence. It provides close-in defence for armored formations using infrared homing missiles.',
      isIndian: false,
    },
    // VERY SHORT RANGE
    {
      name: 'Igla-S (SA-24)',
      countryOfOrigin: 'Russia',
      category: 'VERY_SHORT_RANGE' as const,
      minRange: 0.5,
      maxRange: 6,
      minAltitude: 10,
      maxAltitude: 3500,
      radarType: 'Passive IR Seeker',
      missileType: '9K338 Igla-S',
      mobilityClass: 'MAN_PORTABLE' as const,
      serviceEntryYear: 2004,
      cost: 0.06,
      operatingCostPerHour: 50,
      reloadTime: 10,
      maxSimultaneousTargets: 1,
      accuracy: 0.65,
      interceptorSpeed: 1.8,
      description: 'Igla-S is a man-portable air defence system (MANPADS) in service with the Indian Armed Forces. It provides very short range air defence using infrared-guided missiles that can engage aircraft, helicopters, UAVs, and cruise missiles.',
      isIndian: false,
    },
    {
      name: 'VSHORAD (Mistral)',
      countryOfOrigin: 'France / India',
      category: 'VERY_SHORT_RANGE' as const,
      minRange: 0.3,
      maxRange: 6.5,
      minAltitude: 5,
      maxAltitude: 3000,
      radarType: 'Passive IR Seeker',
      missileType: 'Mistral 2',
      mobilityClass: 'MAN_PORTABLE' as const,
      serviceEntryYear: 2020,
      cost: 0.08,
      operatingCostPerHour: 60,
      reloadTime: 8,
      maxSimultaneousTargets: 1,
      accuracy: 0.7,
      interceptorSpeed: 2.6,
      description: 'India procured MBDA Mistral VSHORAD systems to address the urgent gap in very short range air defence. These are being integrated with indigenous fire control systems for improved effectiveness.',
      isIndian: false,
    },
    {
      name: 'VSHORAD MANPAD',
      countryOfOrigin: 'India',
      category: 'VERY_SHORT_RANGE' as const,
      minRange: 0.5,
      maxRange: 6.5,
      minAltitude: 5,
      maxAltitude: 3500,
      radarType: 'Passive IR Seeker',
      missileType: 'DRDO VSHORAD',
      mobilityClass: 'MAN_PORTABLE' as const,
      serviceEntryYear: 2024,
      cost: 0.1,
      operatingCostPerHour: 50,
      reloadTime: 8,
      maxSimultaneousTargets: 1,
      accuracy: 0.7,
      interceptorSpeed: 2.5,
      description: 'VSHORAD (Very Short Range Air Defence) is an indigenous man-portable air defence system developed by DRDO. It uses a dual-band infrared homing seeker designed to neutralize low-flying tactical threats like helicopters and drones.',
      isIndian: true,
    },
    {
      name: 'RBS-70',
      countryOfOrigin: 'Sweden',
      category: 'VERY_SHORT_RANGE' as const,
      minRange: 0.2,
      maxRange: 8,
      minAltitude: 10,
      maxAltitude: 5000,
      radarType: 'Laser Beam Riding',
      missileType: 'Bolide',
      mobilityClass: 'MAN_PORTABLE' as const,
      serviceEntryYear: 1977,
      cost: 0.15,
      operatingCostPerHour: 80,
      reloadTime: 8,
      maxSimultaneousTargets: 1,
      accuracy: 0.72,
      interceptorSpeed: 2.2,
      description: 'RBS-70 is a Swedish laser-guided VSHORAD system in service with the Indian Army. Its laser beam riding guidance makes it resistant to infrared countermeasures, giving it an advantage against aircraft equipped with flare dispensers.',
      isIndian: false,
    },
    // ANTI-DRONE
    {
      name: 'DRDO Anti-Drone System',
      countryOfOrigin: 'India',
      category: 'ANTI_DRONE' as const,
      minRange: 0.1,
      maxRange: 3,
      minAltitude: 0,
      maxAltitude: 1000,
      radarType: 'Electro-Optical / RF Detector',
      missileType: 'RF Jammer / Laser Dazzler / Hard Kill',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 2020,
      cost: 0.5,
      operatingCostPerHour: 100,
      reloadTime: 2,
      maxSimultaneousTargets: 3,
      accuracy: 0.75,
      interceptorSpeed: 0,
      description: 'DRDO has developed anti-drone systems using a combination of RF detection, electro-optical tracking, RF jamming, laser-based soft kill, and net-based hard kill. These systems were deployed during Republic Day celebrations and other high-security events.',
      isIndian: true,
    },
    {
      name: 'SMASH 2000 Plus',
      countryOfOrigin: 'Israel',
      category: 'ANTI_DRONE' as const,
      minRange: 0.05,
      maxRange: 0.5,
      minAltitude: 0,
      maxAltitude: 300,
      radarType: 'Electro-Optical Smart Sight',
      missileType: 'Kinetic (Rifle-mounted Fire Control)',
      mobilityClass: 'MAN_PORTABLE' as const,
      serviceEntryYear: 2019,
      cost: 0.01,
      operatingCostPerHour: 5,
      reloadTime: 1,
      maxSimultaneousTargets: 1,
      accuracy: 0.85,
      interceptorSpeed: 0,
      description: 'SMASH 2000 Plus is a fire control system that turns standard assault rifles into precision anti-drone weapons. It uses AI algorithms to track moving targets and precisely time the shot to hit small drones.',
      isIndian: false,
    },
    // RADAR SYSTEMS
    {
      name: 'Rohini 3D CAR',
      countryOfOrigin: 'India',
      category: 'RADAR' as const,
      minRange: 0,
      maxRange: 180,
      minAltitude: 0,
      maxAltitude: 18000,
      radarType: '3D Central Acquisition Radar (S-Band)',
      missileType: 'N/A',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 2009,
      cost: 8,
      operatingCostPerHour: 300,
      reloadTime: 0,
      maxSimultaneousTargets: 150,
      accuracy: 0,
      interceptorSpeed: 0,
      description: 'Rohini is an indigenous 3D Central Acquisition Radar developed by BEL and DRDO. It provides long-range surveillance and target data for air defence networks. It can track over 150 targets simultaneously.',
      isIndian: true,
    },
    {
      name: 'Arudhra AESA Radar',
      countryOfOrigin: 'India',
      category: 'RADAR' as const,
      minRange: 0,
      maxRange: 500,
      minAltitude: 0,
      maxAltitude: 30000,
      radarType: 'Active Electronically Scanned Array (S-Band)',
      missileType: 'N/A',
      mobilityClass: 'SEMI_MOBILE' as const,
      serviceEntryYear: 2019,
      cost: 25,
      operatingCostPerHour: 800,
      reloadTime: 0,
      maxSimultaneousTargets: 200,
      accuracy: 0,
      interceptorSpeed: 0,
      description: 'Arudhra is an indigenous AESA radar developed by DRDO for the Indian Air Force. It is designed to replace legacy radars and provides 4D surveillance capability with advanced electronic protection measures.',
      isIndian: true,
    },
    {
      name: 'Aslesha Mk-II',
      countryOfOrigin: 'India',
      category: 'RADAR' as const,
      minRange: 0,
      maxRange: 100,
      minAltitude: 0,
      maxAltitude: 9000,
      radarType: 'Low Level Tracking Radar',
      missileType: 'N/A',
      mobilityClass: 'MOBILE' as const,
      serviceEntryYear: 2015,
      cost: 5,
      operatingCostPerHour: 200,
      reloadTime: 0,
      maxSimultaneousTargets: 100,
      accuracy: 0,
      interceptorSpeed: 0,
      description: 'Aslesha is a low-level tracking radar developed by BEL for the Indian Army Air Defence. It is designed to detect and track low-flying targets that other radars may miss due to terrain masking.',
      isIndian: true,
    },
  ];

  for (const system of systems) {
    await prisma.airDefenceSystem.upsert({
      where: { name: system.name },
      update: system,
      create: system,
    });
  }

  console.log(`✅ ${systems.length} Air Defence Systems seeded`);

  // ---- Seed Threats ----
  const threats = [
    // BALLISTIC MISSILES
    {
      name: 'Shaheen-III',
      type: 'BALLISTIC_MISSILE' as const,
      countryOfOrigin: 'Pakistan',
      speedClass: 'HYPERSONIC' as const,
      maxSpeed: 12.0,
      altitudeClass: 'EXOATMOSPHERIC' as const,
      minAltitude: 0,
      maxAltitude: 150000,
      radarVisibility: 'HIGH' as const,
      rcs: 1.0,
      threatScore: 95,
      costEstimate: 5000,
      range: 2750,
      warheadWeight: 500,
      description: 'Shaheen-III is a medium-range ballistic missile with a reported range of 2,750 km. It is a two-stage solid-fuel missile capable of carrying conventional or nuclear warheads.',
    },
    {
      name: 'Ghauri-II',
      type: 'BALLISTIC_MISSILE' as const,
      countryOfOrigin: 'Pakistan',
      speedClass: 'HYPERSONIC' as const,
      maxSpeed: 10.0,
      altitudeClass: 'EXOATMOSPHERIC' as const,
      minAltitude: 0,
      maxAltitude: 120000,
      radarVisibility: 'VERY_HIGH' as const,
      rcs: 2.0,
      threatScore: 85,
      costEstimate: 3000,
      range: 1800,
      warheadWeight: 700,
      description: 'Ghauri-II (Hatf-VI) is a medium-range ballistic missile. It uses liquid fuel and is based on North Korean Nodong technology. It has a range of approximately 1,800 km.',
    },
    {
      name: 'DF-21D (Educational Reference)',
      type: 'BALLISTIC_MISSILE' as const,
      countryOfOrigin: 'China',
      speedClass: 'HYPERSONIC' as const,
      maxSpeed: 10.0,
      altitudeClass: 'EXOATMOSPHERIC' as const,
      minAltitude: 0,
      maxAltitude: 100000,
      radarVisibility: 'HIGH' as const,
      rcs: 0.8,
      threatScore: 90,
      costEstimate: 10000,
      range: 1770,
      warheadWeight: 600,
      description: 'DF-21D is a medium-range anti-ship ballistic missile. Used here as an educational reference for studying ballistic missile defence concepts. It features maneuverable re-entry vehicle technology.',
    },
    // CRUISE MISSILES
    {
      name: 'Babur-3',
      type: 'CRUISE_MISSILE' as const,
      countryOfOrigin: 'Pakistan',
      speedClass: 'SUBSONIC' as const,
      maxSpeed: 0.8,
      altitudeClass: 'LOW' as const,
      minAltitude: 30,
      maxAltitude: 1000,
      radarVisibility: 'LOW' as const,
      rcs: 0.05,
      threatScore: 80,
      costEstimate: 1500,
      range: 450,
      warheadWeight: 300,
      description: 'Babur-3 is a submarine-launched cruise missile with terrain-hugging flight capability. Its small radar cross-section and low-altitude flight path make it challenging to detect and intercept.',
    },
    {
      name: 'Ra\'ad-II ALCM',
      type: 'CRUISE_MISSILE' as const,
      countryOfOrigin: 'Pakistan',
      speedClass: 'SUBSONIC' as const,
      maxSpeed: 0.85,
      altitudeClass: 'MEDIUM' as const,
      minAltitude: 100,
      maxAltitude: 8000,
      radarVisibility: 'LOW' as const,
      rcs: 0.08,
      threatScore: 75,
      costEstimate: 1200,
      range: 600,
      warheadWeight: 250,
      description: 'Ra\'ad-II is an air-launched cruise missile with a reported range of 600 km. It features low-observable design and terrain-following capability for improved survivability.',
    },
    {
      name: 'CJ-20 ALCM (Educational Reference)',
      type: 'CRUISE_MISSILE' as const,
      countryOfOrigin: 'China',
      speedClass: 'SUBSONIC' as const,
      maxSpeed: 0.9,
      altitudeClass: 'LOW' as const,
      minAltitude: 20,
      maxAltitude: 5000,
      radarVisibility: 'LOW' as const,
      rcs: 0.05,
      threatScore: 82,
      costEstimate: 2000,
      range: 2000,
      warheadWeight: 500,
      description: 'CJ-20 is a long-range air-launched cruise missile. Used as an educational reference for studying cruise missile defence concepts. It features inertial and terrain-contour matching guidance.',
    },
    // UAVs
    {
      name: 'Wing Loong II',
      type: 'UAV' as const,
      countryOfOrigin: 'China',
      speedClass: 'SUBSONIC' as const,
      maxSpeed: 0.28,
      altitudeClass: 'MEDIUM' as const,
      minAltitude: 1000,
      maxAltitude: 9000,
      radarVisibility: 'MEDIUM' as const,
      rcs: 1.0,
      threatScore: 50,
      costEstimate: 2000,
      range: 4000,
      warheadWeight: 480,
      description: 'Wing Loong II is a medium-altitude long-endurance (MALE) UAV capable of ISR and precision strike missions. It has been widely exported and represents a modern armed drone threat.',
    },
    {
      name: 'Generic MALE UAV',
      type: 'UAV' as const,
      countryOfOrigin: 'Generic',
      speedClass: 'SUBSONIC' as const,
      maxSpeed: 0.25,
      altitudeClass: 'MEDIUM' as const,
      minAltitude: 500,
      maxAltitude: 7500,
      radarVisibility: 'MEDIUM' as const,
      rcs: 0.5,
      threatScore: 45,
      costEstimate: 1000,
      range: 1500,
      warheadWeight: 200,
      description: 'A representative medium-altitude long-endurance unmanned aerial vehicle for educational simulation purposes. Features typical ISR and strike capabilities.',
    },
    // DRONE SWARM
    {
      name: 'Generic Drone Swarm (50 units)',
      type: 'DRONE_SWARM' as const,
      countryOfOrigin: 'Generic',
      speedClass: 'SUBSONIC' as const,
      maxSpeed: 0.15,
      altitudeClass: 'LOW' as const,
      minAltitude: 30,
      maxAltitude: 500,
      radarVisibility: 'LOW' as const,
      rcs: 0.01,
      threatScore: 70,
      costEstimate: 500,
      range: 100,
      warheadWeight: 5,
      description: 'A representative drone swarm of 50 small UAVs operating in coordinated formation. Individual drones have very small RCS, making them difficult to detect and engage. The swarm can overwhelm point defence systems through saturation.',
    },
    // FIGHTER AIRCRAFT
    {
      name: 'JF-17 Thunder Block III',
      type: 'FIGHTER_AIRCRAFT' as const,
      countryOfOrigin: 'Pakistan / China',
      speedClass: 'SUPERSONIC' as const,
      maxSpeed: 1.6,
      altitudeClass: 'HIGH' as const,
      minAltitude: 50,
      maxAltitude: 16800,
      radarVisibility: 'HIGH' as const,
      rcs: 3.0,
      threatScore: 65,
      costEstimate: 32000,
      range: 1200,
      warheadWeight: 3600,
      description: 'JF-17 Thunder Block III is a single-engine multirole combat aircraft. Block III features AESA radar, improved avionics, and an integrated electronic warfare suite. It can carry a variety of air-to-air and air-to-ground weapons.',
    },
    {
      name: 'J-10C (Educational Reference)',
      type: 'FIGHTER_AIRCRAFT' as const,
      countryOfOrigin: 'China',
      speedClass: 'SUPERSONIC' as const,
      maxSpeed: 2.0,
      altitudeClass: 'HIGH' as const,
      minAltitude: 50,
      maxAltitude: 18000,
      radarVisibility: 'MEDIUM' as const,
      rcs: 1.5,
      threatScore: 70,
      costEstimate: 45000,
      range: 1600,
      warheadWeight: 6000,
      description: 'J-10C Vigorous Dragon is a single-engine multirole fighter. Used as educational reference. It features AESA radar, reduced RCS, and can launch PL-15 BVR missiles.',
    },
    {
      name: 'F-16 Block 52+ (Educational Reference)',
      type: 'FIGHTER_AIRCRAFT' as const,
      countryOfOrigin: 'USA',
      speedClass: 'SUPERSONIC' as const,
      maxSpeed: 2.0,
      altitudeClass: 'HIGH' as const,
      minAltitude: 50,
      maxAltitude: 15240,
      radarVisibility: 'MEDIUM' as const,
      rcs: 1.2,
      threatScore: 72,
      costEstimate: 70000,
      range: 1500,
      warheadWeight: 7700,
      description: 'F-16 Block 52+ Fighting Falcon is operated by Pakistan Air Force. Used as educational reference for studying air defence against modern fighter aircraft. Features AN/APG-68(V)9 radar and conformal fuel tanks.',
    },
    // BOMBER
    {
      name: 'H-6K (Educational Reference)',
      type: 'BOMBER_AIRCRAFT' as const,
      countryOfOrigin: 'China',
      speedClass: 'SUBSONIC' as const,
      maxSpeed: 0.85,
      altitudeClass: 'HIGH' as const,
      minAltitude: 3000,
      maxAltitude: 12000,
      radarVisibility: 'VERY_HIGH' as const,
      rcs: 30.0,
      threatScore: 80,
      costEstimate: 50000,
      range: 3500,
      warheadWeight: 12000,
      description: 'H-6K is a modernized strategic bomber that can carry cruise missiles. Used as educational reference for studying air defence against bomber threats. It can launch CJ-20 ALCMs from standoff range.',
    },
    // ATTACK HELICOPTER
    {
      name: 'Z-10 (Educational Reference)',
      type: 'ATTACK_HELICOPTER' as const,
      countryOfOrigin: 'China',
      speedClass: 'SUBSONIC' as const,
      maxSpeed: 0.24,
      altitudeClass: 'LOW' as const,
      minAltitude: 10,
      maxAltitude: 6400,
      radarVisibility: 'MEDIUM' as const,
      rcs: 3.0,
      threatScore: 55,
      costEstimate: 20000,
      range: 800,
      warheadWeight: 1500,
      description: 'Z-10 is an attack helicopter used as educational reference. It features tandem cockpit, stub wings for weapons, and reduced radar/IR signature design. Can carry anti-tank missiles and air-to-air missiles.',
    },
    // LOITERING MUNITION
    {
      name: 'Generic Loitering Munition',
      type: 'LOITERING_MUNITION' as const,
      countryOfOrigin: 'Generic',
      speedClass: 'SUBSONIC' as const,
      maxSpeed: 0.2,
      altitudeClass: 'LOW' as const,
      minAltitude: 100,
      maxAltitude: 4500,
      radarVisibility: 'LOW' as const,
      rcs: 0.05,
      threatScore: 55,
      costEstimate: 100,
      range: 200,
      warheadWeight: 15,
      description: 'A representative loitering munition (kamikaze drone) for educational purposes. These low-cost, expendable systems can loiter over a target area and dive onto targets of opportunity.',
    },
    // TACTICAL MISSILE
    {
      name: 'Nasr (Hatf-IX)',
      type: 'TACTICAL_MISSILE' as const,
      countryOfOrigin: 'Pakistan',
      speedClass: 'SUPERSONIC' as const,
      maxSpeed: 3.0,
      altitudeClass: 'MEDIUM' as const,
      minAltitude: 500,
      maxAltitude: 15000,
      radarVisibility: 'HIGH' as const,
      rcs: 0.5,
      threatScore: 75,
      costEstimate: 500,
      range: 70,
      warheadWeight: 200,
      description: 'Nasr (Hatf-IX) is a short-range tactical ballistic missile with a range of approximately 60-70 km. It is a solid-fueled missile designed for battlefield use.',
    },
    // HYPERSONIC
    {
      name: 'Generic Hypersonic Glide Vehicle',
      type: 'HYPERSONIC' as const,
      countryOfOrigin: 'Generic',
      speedClass: 'HYPERSONIC' as const,
      maxSpeed: 8.0,
      altitudeClass: 'VERY_HIGH' as const,
      minAltitude: 20000,
      maxAltitude: 80000,
      radarVisibility: 'LOW' as const,
      rcs: 0.1,
      threatScore: 98,
      costEstimate: 15000,
      range: 2000,
      warheadWeight: 500,
      description: 'A conceptual hypersonic glide vehicle for educational simulation. Hypersonic glide vehicles fly at Mach 5+ in the upper atmosphere, making them extremely difficult to detect and intercept with current technology. Used to study future air defence requirements.',
    },
    {
      name: 'Generic Hypersonic Cruise Missile',
      type: 'HYPERSONIC' as const,
      countryOfOrigin: 'Generic',
      speedClass: 'HYPERSONIC' as const,
      maxSpeed: 6.0,
      altitudeClass: 'HIGH' as const,
      minAltitude: 15000,
      maxAltitude: 35000,
      radarVisibility: 'LOW' as const,
      rcs: 0.08,
      threatScore: 95,
      costEstimate: 12000,
      range: 1500,
      warheadWeight: 300,
      description: 'A conceptual air-breathing hypersonic cruise missile for educational simulation. It uses scramjet propulsion to sustain hypersonic speeds throughout its flight, posing extreme challenges for air defence systems.',
    },
    {
      name: 'F-16 Block 52+',
      type: 'FIGHTER_AIRCRAFT' as const,
      countryOfOrigin: 'USA',
      speedClass: 'SUPERSONIC' as const,
      maxSpeed: 2.0,
      altitudeClass: 'HIGH' as const,
      minAltitude: 50,
      maxAltitude: 15240,
      radarVisibility: 'MEDIUM' as const,
      rcs: 1.2,
      threatScore: 72,
      costEstimate: 40000,
      range: 1500,
      warheadWeight: 7700,
      description: 'Single-engine supersonic multirole combat aircraft. Features highly advanced tactical sensors and options for standoff precision attack weapons.'
    },
    {
      name: 'Mirage III',
      type: 'FIGHTER_AIRCRAFT' as const,
      countryOfOrigin: 'France',
      speedClass: 'SUPERSONIC' as const,
      maxSpeed: 2.2,
      altitudeClass: 'HIGH' as const,
      minAltitude: 50,
      maxAltitude: 17000,
      radarVisibility: 'HIGH' as const,
      rcs: 3.5,
      threatScore: 60,
      costEstimate: 15000,
      range: 1200,
      warheadWeight: 4000,
      description: 'Upgraded retrofitted delta-wing supersonic multirole fighter, capable of carrying stand-off cruise missiles.'
    },
    {
      name: 'Mirage 5',
      type: 'FIGHTER_AIRCRAFT' as const,
      countryOfOrigin: 'France',
      speedClass: 'SUPERSONIC' as const,
      maxSpeed: 2.2,
      altitudeClass: 'HIGH' as const,
      minAltitude: 50,
      maxAltitude: 16000,
      radarVisibility: 'HIGH' as const,
      rcs: 3.2,
      threatScore: 62,
      costEstimate: 18000,
      range: 1300,
      warheadWeight: 4000,
      description: 'Upgraded ROSE-system supersonic ground-attack fighter, optimized for low-level night strike and standoff precision attack.'
    },
    {
      name: 'Shahpar-2',
      type: 'UAV' as const,
      countryOfOrigin: 'Pakistan',
      speedClass: 'SUBSONIC' as const,
      maxSpeed: 0.18,
      altitudeClass: 'MEDIUM' as const,
      minAltitude: 100,
      maxAltitude: 6000,
      radarVisibility: 'MEDIUM' as const,
      rcs: 0.4,
      threatScore: 45,
      costEstimate: 2000,
      range: 1000,
      warheadWeight: 120,
      description: 'Medium-Altitude Long-Endurance (MALE) armed unmanned aerial vehicle developed indigenously by GIDS.'
    },
    {
      name: 'Burraq UAV',
      type: 'UAV' as const,
      countryOfOrigin: 'Pakistan',
      speedClass: 'SUBSONIC' as const,
      maxSpeed: 0.18,
      altitudeClass: 'MEDIUM' as const,
      minAltitude: 100,
      maxAltitude: 7500,
      radarVisibility: 'MEDIUM' as const,
      rcs: 0.5,
      threatScore: 42,
      costEstimate: 1500,
      range: 1000,
      warheadWeight: 100,
      description: 'Armed tactical unmanned combat aerial vehicle developed indigenously, capable of carrying laser-guided missiles.'
    },
    {
      name: 'Ababeel',
      type: 'BALLISTIC_MISSILE' as const,
      countryOfOrigin: 'Pakistan',
      speedClass: 'HYPERSONIC' as const,
      maxSpeed: 15.0,
      altitudeClass: 'EXOATMOSPHERIC' as const,
      minAltitude: 0,
      maxAltitude: 180000,
      radarVisibility: 'HIGH' as const,
      rcs: 1.5,
      threatScore: 99,
      costEstimate: 12000,
      range: 2200,
      warheadWeight: 1500,
      description: 'Medium-range ballistic missile capable of carrying multiple independently targetable reentry vehicles (MIRV) to bypass missile defences.'
    },
    {
      name: 'Ghaznavi',
      type: 'BALLISTIC_MISSILE' as const,
      countryOfOrigin: 'Pakistan',
      speedClass: 'HYPERSONIC' as const,
      maxSpeed: 6.0,
      altitudeClass: 'EXOATMOSPHERIC' as const,
      minAltitude: 0,
      maxAltitude: 80000,
      radarVisibility: 'HIGH' as const,
      rcs: 0.8,
      threatScore: 80,
      costEstimate: 4000,
      range: 290,
      warheadWeight: 700,
      description: 'Short-range solid-fueled tactical ballistic missile with rapid deployment and dive capabilities.'
    },
    {
      name: 'CM-302',
      type: 'CRUISE_MISSILE' as const,
      countryOfOrigin: 'China',
      speedClass: 'SUPERSONIC' as const,
      maxSpeed: 3.0,
      altitudeClass: 'LOW' as const,
      minAltitude: 20,
      maxAltitude: 50,
      radarVisibility: 'LOW' as const,
      rcs: 0.08,
      threatScore: 85,
      costEstimate: 3000,
      range: 290,
      warheadWeight: 250,
      description: 'Supersonic anti-ship and land-attack cruise missile, flying a low sea-skimming trajectory.'
    },
    {
      name: 'Harbah',
      type: 'CRUISE_MISSILE' as const,
      countryOfOrigin: 'Pakistan',
      speedClass: 'SUBSONIC' as const,
      maxSpeed: 0.8,
      altitudeClass: 'LOW' as const,
      minAltitude: 20,
      maxAltitude: 50,
      radarVisibility: 'LOW' as const,
      rcs: 0.04,
      threatScore: 78,
      costEstimate: 1800,
      range: 750,
      warheadWeight: 300,
      description: 'Indigenous subsonic land-attack and anti-ship cruise missile, flying low to bypass radar grids.'
    },
    {
      name: 'CH-901',
      type: 'LOITERING_MUNITION' as const,
      countryOfOrigin: 'China',
      speedClass: 'SUBSONIC' as const,
      maxSpeed: 0.12,
      altitudeClass: 'LOW' as const,
      minAltitude: 100,
      maxAltitude: 1500,
      radarVisibility: 'LOW' as const,
      rcs: 0.02,
      threatScore: 52,
      costEstimate: 100,
      range: 15,
      warheadWeight: 3.5,
      description: 'Miniature loitering munition designed for target scouting and precision kamikaze strike.'
    }
  ];

  for (const threat of threats) {
    await prisma.threat.upsert({
      where: { name: threat.name },
      update: threat,
      create: threat,
    });
  }

  console.log(`✅ ${threats.length} Threats seeded`);

  // ---- Seed Default Scenario ----
  const defaultScenario = await prisma.scenario.create({
    data: {
      name: 'Delhi NCR Defence Scenario',
      description: 'Educational scenario simulating layered air defence of the Delhi National Capital Region. Uses publicly known information about the general area and educational approximations.',
      isPublic: true,
      userId: admin.id,
      mapConfig: {
        centerLat: 28.6139,
        centerLng: 77.2090,
        zoom: 8,
        zones: [
          { id: 'z1', name: 'New Delhi', type: 'CITY', lat: 28.6139, lng: 77.2090, radius: 30, value: 100 },
          { id: 'z2', name: 'Palam Air Force Station', type: 'AIRBASE', lat: 28.5665, lng: 77.0910, radius: 5, value: 85 },
          { id: 'z3', name: 'Hindon Air Force Station', type: 'AIRBASE', lat: 28.7000, lng: 77.3600, radius: 5, value: 80 },
          { id: 'z4', name: 'Noida Industrial Zone', type: 'INDUSTRIAL', lat: 28.5355, lng: 77.3910, radius: 15, value: 60 },
          { id: 'z5', name: 'Gurgaon Tech Hub', type: 'INFRASTRUCTURE', lat: 28.4595, lng: 77.0266, radius: 10, value: 55 },
        ],
      },
      defenderSetup: {
        systems: [],
        budget: 500,
      },
      attackerSetup: {
        waves: [
          {
            id: 'w1',
            time: 30,
            threats: [
              { threatId: '', count: 4, targetZoneId: 'z1', launchLat: 30.5, launchLng: 72.0 },
            ],
          },
          {
            id: 'w2',
            time: 90,
            threats: [
              { threatId: '', count: 2, targetZoneId: 'z2', launchLat: 31.0, launchLng: 73.0 },
              { threatId: '', count: 6, targetZoneId: 'z1', launchLat: 29.5, launchLng: 71.5 },
            ],
          },
        ],
        budget: 200,
      },
    },
  });

  console.log('✅ Default scenario seeded');
  console.log('\n🎉 Database seeding complete!');
  console.log(`   Admin login: admin@iades.edu / admin123`);
  console.log(`   Demo login: demo@iades.edu / demo123`);
}

main()
  .catch((e) => {
    console.error('❌ Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
